### ISSUE TITLE
Request additions

### ISSUE THREAD

**Issue by AiWABR** [DoctorD1501/JAVMovieScraper#1]
Some suggestions and requests:

1 When ordering your poster image that is not the fanart. Or both, in order poster and fanart later.
Place 2 more option for editing and the scrapper is made as Studio, Parents, Genres, Parental rating.
Option 3 manually edit actors, add that does not come. (As often happens with those who did not have thumb on the data18).
4 One way to look at the scene by id data18.
Ex: http://www.data18.com/content/1129580 - the id of the scene is 112958
If you do not find the name of the scene, we can put the id that took the data18.
5 Edit the title to seek power, sometimes the main site (bangbros and other), change the title and can not find the old name.

I think that's what got me to remember while using the program. If you can add would show.

But thanks again for the great work, both in the xbmc scrapper as for this wonderful program. 

Request also made ​​on the official forum thread XBMC 

http://forum.xbmc.org/showthread.php?tid=200788&page=2

**Comment by DoctorD1501** [comment]
I've added a method of putting in a URL manually when scraping in 7dfe6703a2193acc646b9b553b1717d3cce1ab59

**Comment by AiWABR** [comment]
Thanks DoctorD1501
