### ISSUE TITLE
Data18 movie scrapper bringing in unwanted genre info

### ISSUE THREAD

**Issue by myxtrastufff** [DoctorD1501/JAVMovieScraper#100]
Scraping movies with data18 movie scraper is bringing in unwanted info in the genres section. For example sale prices on the site. This happens on ver 1.36 and 2.03. So I assume this was a change in the website?

**Comment by DoctorD1501** [comment]
I had released a fix for this in my beta build available on mediafire, but the fix hadn't made it into an official build yet.

 I just made a release now (0.2.04-alpha) which you can grab that should have the fix. If you're still having issues with this after getting 0.2.04-alpha, please let me know.

Thanks.
