### ISSUE TITLE
Suggestion set support for emby

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#101]
I'm trying to move over to Emby from MySQL. For sets(boxset collection on emby) it uses <collectionnumber></collectionnumber>. Instead of <set></set>. Which every thing else uses. It's really bugging me. Also actor thumbs are saved to one folder. Instead of the movie folder. I'm liking emby but the few things they have changed are making it hard on my already scrapped data. As it can rescrape movies easy. Porn is my only problem with the metadata.

**Comment by DoctorD1501** [comment]
I think your HTML tags got stripped out. Can you reformat your post to make it a little more clear?

**Comment by mjsmjs** [comment]
it uses (collectionnumber)(/collectionnumber) instead of (set)(/set). It grabs the number id from themoviedb instead of the collection name. But the collection name will still work it just has to be in (collectionnumber)Fast and Furious(/collectionnumber)

**Comment by DoctorD1501** [comment]
Isn't this a limitation of the emby program itself?

See this forum post for more info:

http://emby.media/community/index.php?/topic/10724-movie-set-field-in-nfo/

 The collection number is just supposed to be that - a number. Using a set there is not the intended use of that field and you're putting in information into that field that doesn't belong. Sure, it'll display what you want for now, but if they add the set field later on down the road you're going to have weirdly duplicated data. The real solution would be for Emby to use the set tag, as that forum post indicates.

For the actor thumb thing, you may be able to just search for all folders named ".actors" in your scraped movie folder. That will give you list of folders. Copy all those folders to a completely different directory. Then within that directory, search for "*.jpg". Then from those search results, you'll get all the actor names. Copy all the files to your Emby actors folder. It's not great, but it should work. 

Doesn't emby read the actors from the nfo anyways if it can't find it? Does it have a way to write out the info to files like Kodi does where it can export the library as separate files?

**Comment by mjsmjs** [comment]
When creating a collection in emby it just adds a name to the collection number field. Since there isn't much porn on themoviedb I don't see a problem. If they ever start using the set tag they might add a option for which field is used over the other. I used Notepad++ to rename (set)(/set) to (collectionnumber)(/collectionnumber) on a few movies. To see if it would work. I don't see a problem of having both fields (sets) and (collectionnumbers).

The actor thumbs are sorted alphabetically. Emby will read the name but not the thumb from the nfo. It only searches themoviedb and thetvdb for actors. the thumbs are saved as ImagesByName/People/W/Will Smith/poster.jpg and person.xml. So its not as simple as just copying the current thumbs.

**Comment by Wizell** [comment]
Kodi metadata format (which is used by JMS) doesn't have specification for "collectionumber". So nfo files will not contain this tag.

If you ask to support another output format decidated to emby, please give informations about this format like a page to the description/specification of this format
