### ISSUE TITLE
Suggestion poster size

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#106]
With the web scrapper set to auto grab artwork it picks the first one. Any way you can make it to grab the poster size instead of the thumb size?

**Comment by DoctorD1501** [comment]
Which scraper are you seeing grab the thumbnail size? And what is the file you are scraping that returns just a thumbnail? It's not supposed to be doing that.

**Comment by DoctorD1501** [comment]
I'm closing this issue - please reopen a new issue if you see this happening for a specific scraper.

Thank you.
