### ISSUE TITLE
Can't scape years and release day in some specific scaper!

### ISSUE THREAD

**Issue by nk0304** [DoctorD1501/JAVMovieScraper#107]
Hello DoctorD!

I just tried scaper from build 0.2.00 to newest build and it can't scape years and release day in caribbean scaper, and dmm scaper can't scape ID of movie too. I don't know about other specific scaper, haven't tried it yet. But when i use build 0.1.35 everything is working fine. Can you check this please, and thank you for making awesome tool.

**Comment by DoctorD1501** [comment]
Can you give me some example file names that aren't working for you? Thanks.

**Comment by nk0304** [comment]
For example 072615-930 and ABP-288, i add some screenshot too, in case you need it.
![1](https://cloud.githubusercontent.com/assets/9572542/9269755/b2515d52-4296-11e5-855b-382b7b3043fa.jpg)
![2](https://cloud.githubusercontent.com/assets/9572542/9269757/b3b9e7ae-4296-11e5-9b09-d29c97639226.jpg)

**Comment by DoctorD1501** [comment]
I added a fix on the newest build from  http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar  for the Caribbean release date problem. However, I'm not seeing the issue with the ID not scraping for that JAV movie. Can you try deleting your AmalgamationSettings.json file and settings.xml and scraping the file again with the newest build?

If it still doesn't show the ID, can you post the log that you see when clicking "View" menu then "Show Output in New Window"?

Thanks.

**Comment by nk0304** [comment]
Caribbean is working fine now but DMM scaper still can't scape ID, please note that i'm using DMM scraper only, R18 scaper is working fine, this is log file:

Read in amalgamation preferences from AmalgamationSettings.json
currentItemSource = R18.com with disabled = false
currentItemSource = JavLibrary with disabled = false
currentItemSource = JavZoo with disabled = false
currentItemSource = SquarePlus with disabled = false
currentItemSource = ActionJav with disabled = false
currentItemSource = DMM.co.jp with disabled = false
currentItemSource = Default Data Item Source with disabled = false
Scraping this webpage for movie: http://www.dmm.co.jp/mono/dvd/-/detail/=/cid=118abp288/?i3_ref=search&i3_ord=2
There should be a trailer, searching now...
Trailer existed at: http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4
Movie scraped = Movie [title=Title [title="?????????? ????????? ?????" source="DMM.co.jp"], originalTitle=OriginalTitle [originalTitle="?????????? ????????? ?????" source="DMM.co.jp"], sortTitle=SortTitle [sortTitle="" source="DMM.co.jp"], set=Set [set="?????????? ?????????" source="DMM.co.jp"], rating=Rating [maxRating="5.0", rating="4.20"  source="DMM.co.jp"], year=Year [year="2015" source="DMM.co.jp"], top250=Top250 [top250="" source="DMM.co.jp"], trailer = Trailer [trailer="http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4" source="DMM.co.jp"], votes=Votes [votes="5" source="DMM.co.jp"], outline=Outline [outline="" source="DMM.co.jp"], plot=Plot [plot="????????????? ???? ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ??????????????????????????????????????????????????????????????????????????????????????" source="DMM.co.jp"], tagline=Tagline [tagline="" source="DMM.co.jp"], studio=Studio [studio="ABSOLUTELY PERFECT" source="DMM.co.jp"]releaseDate=ReleaseDate [releasedate="2015-04-22" source="DMM.co.jp"], runtime=Runtime [runtime="" source="DMM.co.jp"], posters=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], fanart=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="DMM.co.jp"], id=ID [id="" source="DMM.co.jp"], genres=[Genre [genre="???" source="DMM.co.jp"], Genre [genre="????" source="DMM.co.jp"], Genre [genre="?????" source="DMM.co.jp"]], actors=[Actor [role="", Person [name="?????", thumb=Thumb [thumbURL=http://pics.dmm.co.jp/mono/actjpgs/kizuki_anri.jpg" source="Default Data Item Source"]] source="DMM.co.jp"]], directors=[Director [toString()=Person [name="????????", thumb=null] ," source="DMM.co.jp""]]]
Scraping complete of siteScraper = DMM.co.jp
Read in amalgamation preferences from AmalgamationSettings.json
Skipping amalgamation process as there is only one movie
Setting new movie: Movie [title=Title [title="?????????? ????????? ?????" source="DMM.co.jp"], originalTitle=OriginalTitle [originalTitle="?????????? ????????? ?????" source="DMM.co.jp"], sortTitle=SortTitle [sortTitle="" source="DMM.co.jp"], set=Set [set="?????????? ?????????" source="DMM.co.jp"], rating=Rating [maxRating="5.0", rating="4.20"  source="DMM.co.jp"], year=Year [year="2015" source="DMM.co.jp"], top250=Top250 [top250="" source="DMM.co.jp"], trailer = Trailer [trailer="http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4" source="DMM.co.jp"], votes=Votes [votes="5" source="DMM.co.jp"], outline=Outline [outline="" source="DMM.co.jp"], plot=Plot [plot="????????????? ???? ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ??????????????????????????????????????????????????????????????????????????????????????" source="DMM.co.jp"], tagline=Tagline [tagline="" source="DMM.co.jp"], studio=Studio [studio="ABSOLUTELY PERFECT" source="DMM.co.jp"]releaseDate=ReleaseDate [releasedate="2015-04-22" source="DMM.co.jp"], runtime=Runtime [runtime="" source="DMM.co.jp"], posters=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], fanart=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="DMM.co.jp"], id=ID [id="" source="DMM.co.jp"], genres=[Genre [genre="???" source="DMM.co.jp"], Genre [genre="????" source="DMM.co.jp"], Genre [genre="?????" source="DMM.co.jp"]], actors=[Actor [role="", Person [name="?????", thumb=Thumb [thumbURL=http://pics.dmm.co.jp/mono/actjpgs/kizuki_anri.jpg" source="Default Data Item Source"]] source="DMM.co.jp"]], directors=[Director [toString()=Person [name="????????", thumb=null] ," source="DMM.co.jp""]]]
Read in amalgamation preferences from AmalgamationSettings.json
currentItemSource = R18.com with disabled = false
currentItemSource = JavLibrary with disabled = false
currentItemSource = JavZoo with disabled = false
currentItemSource = SquarePlus with disabled = false
currentItemSource = ActionJav with disabled = false
currentItemSource = DMM.co.jp with disabled = false
currentItemSource = Default Data Item Source with disabled = false
Scraping this webpage for movie: http://www.dmm.co.jp/mono/dvd/-/detail/=/cid=118abp288/?i3_ref=search&i3_ord=2
There should be a trailer, searching now...
Trailer existed at: http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4
Movie scraped = Movie [title=Title [title="Life's first-trance super Iki climax sex Terutsuki Anri" source="DMM.co.jp"], originalTitle=OriginalTitle [originalTitle="?????????? ????????? ?????" source="DMM.co.jp"], sortTitle=SortTitle [sortTitle="" source="DMM.co.jp"], set=Set [set="Life's first-trance super Iki cum sex" source="DMM.co.jp"], rating=Rating [maxRating="5.0", rating="4.20"  source="DMM.co.jp"], year=Year [year="2015" source="DMM.co.jp"], top250=Top250 [top250="" source="DMM.co.jp"], trailer = Trailer [trailer="http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4" source="DMM.co.jp"], votes=Votes [votes="5" source="DMM.co.jp"], outline=Outline [outline="" source="DMM.co.jp"], plot=Plot [plot="Prestige exclusive actress "Terutsuki Anri" is, is open the erogenous to the limit many times Acme climax! And subjected to hypnosis in school uniform appearance, it is obsessed with sex in a pseudo-love mode! And accustomed to sex from being stimulating the sensitive places in the mouth of the soft palateIf, and rolled breath and weakness while convulsions in the piston of pleasure! It would have been driven and to be committed in helpless state! This unequaled actor who gathered for the work is implanted in Kanpatsu Irezu continuous, and go mad yoga to shout! Human experimentation just likeIs Ajiwa the pleasure of outstanding experience one after another, the figure to continue scraping algae drooling is a masterpiece! !" source="DMM.co.jp"], tagline=Tagline [tagline="" source="DMM.co.jp"], studio=Studio [studio="ABSOLUTELY PERFECT" source="DMM.co.jp"]releaseDate=ReleaseDate [releasedate="2015-04-22" source="DMM.co.jp"], runtime=Runtime [runtime="" source="DMM.co.jp"], posters=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], fanart=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="DMM.co.jp"], id=ID [id="" source="DMM.co.jp"], genres=[Genre [genre="School uniform" source="DMM.co.jp"], Genre [genre="Single piece" source="DMM.co.jp"], Genre [genre="Hypnosis, brainwashing" source="DMM.co.jp"]], actors=[Actor [role="", Person [name="Anri Kizuki", thumb=Thumb [thumbURL=http://pics.dmm.co.jp/mono/actjpgs/kizuki_anri.jpg" source="Default Data Item Source"]] source="DMM.co.jp"]], directors=[Director [toString()=Person [name="Manhattan Kimura", thumb=null] ," source="DMM.co.jp""]]]
Scraping complete of siteScraper = DMM.co.jp
Read in amalgamation preferences from AmalgamationSettings.json
Skipping amalgamation process as there is only one movie
Setting new movie: Movie [title=Title [title="Life's first-trance super Iki climax sex Terutsuki Anri" source="DMM.co.jp"], originalTitle=OriginalTitle [originalTitle="?????????? ????????? ?????" source="DMM.co.jp"], sortTitle=SortTitle [sortTitle="" source="DMM.co.jp"], set=Set [set="Life's first-trance super Iki cum sex" source="DMM.co.jp"], rating=Rating [maxRating="5.0", rating="4.20"  source="DMM.co.jp"], year=Year [year="2015" source="DMM.co.jp"], top250=Top250 [top250="" source="DMM.co.jp"], trailer = Trailer [trailer="http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4" source="DMM.co.jp"], votes=Votes [votes="5" source="DMM.co.jp"], outline=Outline [outline="" source="DMM.co.jp"], plot=Plot [plot="Prestige exclusive actress "Terutsuki Anri" is, is open the erogenous to the limit many times Acme climax! And subjected to hypnosis in school uniform appearance, it is obsessed with sex in a pseudo-love mode! And accustomed to sex from being stimulating the sensitive places in the mouth of the soft palateIf, and rolled breath and weakness while convulsions in the piston of pleasure! It would have been driven and to be committed in helpless state! This unequaled actor who gathered for the work is implanted in Kanpatsu Irezu continuous, and go mad yoga to shout! Human experimentation just likeIs Ajiwa the pleasure of outstanding experience one after another, the figure to continue scraping algae drooling is a masterpiece! !" source="DMM.co.jp"], tagline=Tagline [tagline="" source="DMM.co.jp"], studio=Studio [studio="ABSOLUTELY PERFECT" source="DMM.co.jp"]releaseDate=ReleaseDate [releasedate="2015-04-22" source="DMM.co.jp"], runtime=Runtime [runtime="" source="DMM.co.jp"], posters=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], fanart=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="DMM.co.jp"], id=ID [id="" source="DMM.co.jp"], genres=[Genre [genre="School uniform" source="DMM.co.jp"], Genre [genre="Single piece" source="DMM.co.jp"], Genre [genre="Hypnosis, brainwashing" source="DMM.co.jp"]], actors=[Actor [role="", Person [name="Anri Kizuki", thumb=Thumb [thumbURL=http://pics.dmm.co.jp/mono/actjpgs/kizuki_anri.jpg" source="Default Data Item Source"]] source="DMM.co.jp"]], directors=[Director [toString()=Person [name="Manhattan Kimura", thumb=null] ," source="DMM.co.jp""]]]
Read in amalgamation preferences from AmalgamationSettings.json
currentItemSource = R18.com with disabled = false
currentItemSource = JavLibrary with disabled = false
currentItemSource = JavZoo with disabled = false
currentItemSource = SquarePlus with disabled = false
currentItemSource = ActionJav with disabled = false
currentItemSource = DMM.co.jp with disabled = false
currentItemSource = Default Data Item Source with disabled = false
Scraping this webpage for movie: http://www.dmm.co.jp/mono/dvd/-/detail/=/cid=118abp288/?i3_ref=search&i3_ord=2
There should be a trailer, searching now...
Trailer existed at: http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4
Movie scraped = Movie [title=Title [title="?????????? ????????? ?????" source="DMM.co.jp"], originalTitle=OriginalTitle [originalTitle="?????????? ????????? ?????" source="DMM.co.jp"], sortTitle=SortTitle [sortTitle="" source="DMM.co.jp"], set=Set [set="?????????? ?????????" source="DMM.co.jp"], rating=Rating [maxRating="5.0", rating="4.20"  source="DMM.co.jp"], year=Year [year="2015" source="DMM.co.jp"], top250=Top250 [top250="" source="DMM.co.jp"], trailer = Trailer [trailer="http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4" source="DMM.co.jp"], votes=Votes [votes="5" source="DMM.co.jp"], outline=Outline [outline="" source="DMM.co.jp"], plot=Plot [plot="????????????? ???? ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ??????????????????????????????????????????????????????????????????????????????????????" source="DMM.co.jp"], tagline=Tagline [tagline="" source="DMM.co.jp"], studio=Studio [studio="ABSOLUTELY PERFECT" source="DMM.co.jp"]releaseDate=ReleaseDate [releasedate="2015-04-22" source="DMM.co.jp"], runtime=Runtime [runtime="" source="DMM.co.jp"], posters=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], fanart=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="DMM.co.jp"], id=ID [id="" source="DMM.co.jp"], genres=[Genre [genre="???" source="DMM.co.jp"], Genre [genre="????" source="DMM.co.jp"], Genre [genre="?????" source="DMM.co.jp"]], actors=[Actor [role="", Person [name="?????", thumb=Thumb [thumbURL=http://pics.dmm.co.jp/mono/actjpgs/kizuki_anri.jpg" source="Default Data Item Source"]] source="DMM.co.jp"]], directors=[Director [toString()=Person [name="????????", thumb=null] ," source="DMM.co.jp""]]]
Scraping complete of siteScraper = DMM.co.jp
Read in amalgamation preferences from AmalgamationSettings.json
Skipping amalgamation process as there is only one movie
Setting new movie: Movie [title=Title [title="?????????? ????????? ?????" source="DMM.co.jp"], originalTitle=OriginalTitle [originalTitle="?????????? ????????? ?????" source="DMM.co.jp"], sortTitle=SortTitle [sortTitle="" source="DMM.co.jp"], set=Set [set="?????????? ?????????" source="DMM.co.jp"], rating=Rating [maxRating="5.0", rating="4.20"  source="DMM.co.jp"], year=Year [year="2015" source="DMM.co.jp"], top250=Top250 [top250="" source="DMM.co.jp"], trailer = Trailer [trailer="http://cc3001.dmm.co.jp/litevideo/freepv/1/118/118abp288/118abp288_dmb_w.mp4" source="DMM.co.jp"], votes=Votes [votes="5" source="DMM.co.jp"], outline=Outline [outline="" source="DMM.co.jp"], plot=Plot [plot="????????????? ???? ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ??????????????????????????????????????????????????????????????????????????????????????" source="DMM.co.jp"], tagline=Tagline [tagline="" source="DMM.co.jp"], studio=Studio [studio="ABSOLUTELY PERFECT" source="DMM.co.jp"]releaseDate=ReleaseDate [releasedate="2015-04-22" source="DMM.co.jp"], runtime=Runtime [runtime="" source="DMM.co.jp"], posters=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], fanart=[Thumb [thumbURL=http://pics.dmm.co.jp/mono/movie/adult/118abp288/118abp288pl.jpg" source="DMM.co.jp"]], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="DMM.co.jp"], id=ID [id="" source="DMM.co.jp"], genres=[Genre [genre="???" source="DMM.co.jp"], Genre [genre="????" source="DMM.co.jp"], Genre [genre="?????" source="DMM.co.jp"]], actors=[Actor [role="", Person [name="?????", thumb=Thumb [thumbURL=http://pics.dmm.co.jp/mono/actjpgs/kizuki_anri.jpg" source="Default Data Item Source"]] source="DMM.co.jp"]], directors=[Director [toString()=Person [name="????????", thumb=null] ," source="DMM.co.jp""]]]

**Comment by DoctorD1501** [comment]
Ah, I see the problem in the DMM scraper. I just posted a new build on  http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar that should fix the issue.

Thanks for the bug report.
