### ISSUE TITLE
1pondo and javbus can not work

### ISSUE THREAD

**Issue by ws01459293** [DoctorD1501/JAVMovieScraper#110]
1pondo and javbus can not work! help!thank you!

**Comment by DoctorD1501** [comment]
What is the name of the file you are trying with javbus? It's working fine for me.

There's already an existing issue (Issue #87) for issues with 1Pondo. The issue has to do with the fact that they reorganized their movie naming structure and I'd need to spend some time figuring out how to redo the scraper to support both types of names.

**Comment by ws01459293** [comment]
forexample：it's all films in 10musume.com or 1pondo.com for trying with javbus.There are many other codeless films

**Comment by DoctorD1501** [comment]
This issue is resolved in my latest commit and will be included in the v0.2.10 release.
