### ISSUE TITLE
Enhancement: Create (empty) .NFO files even if the scraper did not find information

### ISSUE THREAD

**Issue by madaustrian** [DoctorD1501/JAVMovieScraper#111]
Hi,

Thanks for your work and this program - very appreciated.

Would it be possible to create a .NFO file (via the write file data button) if the scraper did not find information?

I would want the current file name a move title and also whatever information I supply in genres and other fields...

Further down the road maybe either:

a) create a thumbnail for poster & fanart

- or -

b) supply fanart & poster by choosing a file from a list/directory.

- and, what I would like a lot:

c) adding genres also with predefined fields (read from a settings file) with a dropdown box or checkbox list (nice, you can add more in 1 run).

I believe that you already have the system for writing this xml data in place but my knowledge of Java is far too little to contribute efficiently ...

Thank you and keep on going please :)

**Comment by DoctorD1501** [comment]
It's not outside the realm of possibility, but I wonder if you might have an easier time using a other, more full featured movie scraper program such as Ember Media Manager or Media Companion. I'm not intending to write a replacement program for library management or write nearly as many features as those programs already have, mostly just due to the time it would take to write all that stuff and maintain the features. If anyone else wants to contribute these features to this project, however, I would gladly review the code and merge changes in if they work well enough.

**Comment by madaustrian** [comment]
I tied the other software already - they are just too clumsy - your's is lightweight and easy to work with...

As a start - it would be super useful if your program could just generate a .nfo file with data I submit if the scrape did not find any information. It works very well if the scraper sucessfully gets something - but if not - the .nfo file is not written for further processing... 
AND: it also works if I generate a .nfo file by hand and then change/add values 
:)
I am already trying to enhance my java knowledge - but, of course this will take a little longer than planned...

**Comment by madaustrian** [comment]
OK - so part of my request I could build after playing with Java & Eclipse :)

I am not sure if you are interested in this - I "enhanced" your add genre dialog by a list of fixed items that are independently slectable.

Let me know and I will send you the source code.

![add_new_genre](https://cloud.githubusercontent.com/assets/15178888/10930863/b74ef00a-82c2-11e5-9e4a-47b2deb47585.jpg)

**Comment by DoctorD1501** [comment]
It might make more sense to read in the list of check boxes from a user defined genres text file or json file rather than have them hard coded. That way, there can be a genre edit screen so the user can pick what they like. Also, the check boxes would need to be laid out in the dialog in some way that could support more than one screen full of stuff in case the user adds a bunch of stuff. That probably means a scroll bar or something.

Otherwise, this looks like it could be pretty cool in terms of saving time typing stuff.

**Comment by madaustrian** [comment]
I would love to have it in an xml file (or file of sorts) - but really, my knowledge of Java is super limited, and my wife is already asking :)
I used:
	private JCheckBox[] GenreButton_1;
...	private JCheckBox[] GenreButton_4;
	
	private String GenreList_1[];
...	private String GenreList_4[];
	
	private int NumberOfItems_1; 
...	private int NumberOfItems_4;

within 
private JPanel initializeInnerFrame(Genre genreToEdit)
I define:

GenreList_1 = new String[]{
				"JAV", 
				"Uncensored", 
				"Censored", 
				
				"Beautiful Pussy",
				"Hairy Pussy",	
				"Shaved Pussy",


				
				"Big Nipples", 
				"Small Breasts",
				"Big Breasts",
				"Breast Milk"
			};

NumberOfItems_1 = GenreList_1.length;
GenreButton_1 = new JCheckBox[NumberOfItems_1];

The buttons I add by:
	for (int i=0 ; i < NumberOfItems_1; i++){
			gbc_check.gridx = 1;
			gbc_check.gridy = 2+i;
			GenreButton_1[i] = new JCheckBox(GenreList_1[i]);
			GenreButton_1[i].setSelected(false);
			innerPanel.add(GenreButton_1[i], gbc_check);	
		}

This way I have 4 columns with different length which can easily be added to the panel and gives some sort of 'fine' tuning/ordering.

Currently I have no idea how to fill this logic into the use of an external file but will think about it.
(of course hard coded is easier...*ggg*)

**Comment by madaustrian** [comment]
Done - I have (a little rude code) achieved to put the genre list into an xml file (and even create a file if it does not exist - with only 1 item though).
How could I submit the code to you for review and possible inclusion? 
(it needs changes to more than 1 file)..

**Comment by DoctorD1501** [comment]
Submit a pull request on github. This page has info if you haven't done this before:

https://help.github.com/articles/using-pull-requests/

**Comment by madaustrian** [comment]
Was a litle challenging  :)
Did you receive the pull request?

**Comment by DoctorD1501** [comment]
Yeah, I got it. It may take me a little while to look it over and incorporate the changes though with some changes. I'm probably not going to create a new specific scraper like you did but just allow you to edit a movie that doesn't have scraped info. Also, for the checkbox persistent storage, I'm going to reuse the existing preference file so we don't need to add a bunch of new xml serialization code and then add a gui to add your own genres.

Thanks!

**Comment by DoctorD1501** [comment]
The last part of this is now done in 31c1c8aa57a00546bc2058f095d473d5674fa6b9. You should now be able to edit blank movies as you please.
