### ISSUE TITLE
JAVBUS Uncensored Scraped information missing

### ISSUE THREAD

**Issue by unknown12345678** [DoctorD1501/JAVMovieScraper#116]
JAVBUS now includes ID and GENRE information for uncensored content. JAVMovieScraper doesn't seem to be pulling in this information.

I can only assume the JAVBUS website database for uncensored content has been recently updated to include this information.

JAVBUS is invaluable for all uncensored content seeing as you don't have to scrape individually (e.g. 1pondo, carribean etc)

**Comment by DoctorD1501** [comment]
I've made some updates that you can see in the commit attached to this task. Javbus made some changes on their end that broke a few of the scraper fields. This fix will be included in the v0.2.12-alpha release.

**Comment by unknown12345678** [comment]
Thanks DoctorD! Really appreciate all the work you've done with this. Can't survive without this tool.

**Comment by DoctorD1501** [comment]
By the way, you can get the newest build with this fix included from mediafire if you want to get this ASAP. Here's the URL:

http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

The actual 0.2.12-alpha release will likely have some other stuff thrown in.
