### ISSUE TITLE
Multiple File Scraping - Edit Results of All Files, Not Just Last File

### ISSUE THREAD

**Issue by DarkMask100** [DoctorD1501/JAVMovieScraper#118]
We have the ability to scrape multiple files at once but I've noticed we can only make edits to the last file scrapped. When multi-scraping I'd like to suggest the ability to view results of the scrape for each file, make changes where needed and have it write the file data all at once.

**Comment by DoctorD1501** [comment]
I added this feature in e9ee873692bd6350d02eca85bf445c110fb60784. Maybe in the future I can also give the user a button to discard or rescrape just one file in a multi batch.
