### ISSUE TITLE
moving/renaming files on networkshares does not work

### ISSUE THREAD

**Issue by sabbeldacks** [DoctorD1501/JAVMovieScraper#119]
files on networkshares (e.g. \\pc-name\share\directory\file.name ) are moved/renamed to wrong location.
In moviescraper.doctord.controller.Renamer.java function: getRenamedFolderPath the code (line 109) newPath.replace(doublePathSeperator, File.separator) manipulates even the beginning and invalidates the networkshare to \pc-name\... (only one slash at the beginning; java falls back to the drive letter from which the Scraper is started, so no error occurs using the wrong path).
Instead of (line 72) path = getRenamedFolderPath(path), a better way would be
path = FilenameUtils.getPrefix(oldFile.toString()) + getRenamedFolderPath(FilenameUtils.getPath(oldFile.toString()));
This seperates the share or drive letter from the path (using FilenameUtils.getPath() instead of FilenameUtil.getFullPath()).

**Comment by DoctorD1501** [comment]
Thanks for the bug report. I've submitted a new version of Renamer.java which fixes this issue. It ended up being a slightly different fix than your suggestion since this also needed to work with drive letters too, but the idea is the same as what you recommended!
