### ISSUE TITLE
Multiple file scraping freeze

### ISSUE THREAD

**Issue by shad00m** [DoctorD1501/JAVMovieScraper#121]
v0.2.13-alpha - Java 8.66 - Windows 10 x64

1. I've selected about 33 Files
2. Clicked "Scrape Adult Amalgamated JAV Censored Group"
3. Wrote file data after it was done scraping
4. it wrote all the file data but it froze with 50% CPU load (dual core), 30 Threads and about 250mb of ram and have to force close it.

Sorry there is no error to this but I reproduced it with the same amount of files. I'm not sure where the limits are I'll post here after further testing

30 files = stopped scraping at the 26th file
20 files = 3 scrappings, all fine
15 files = 3 scrapings, all fine
10 files = 3 scrapings all fine

**Comment by DoctorD1501** [comment]
Nothing in the error logs, eh?

By any chance, do you have "write trailers to file enabled"?

Also, if you scrape the file that it stops on individually, it works right?

Would it be possible to post the JAV IDs (you don't need the titles) of the 30 files to pastebin or something similar and link it here so I can see if I can recreate the error?

Thanks.

**Comment by shad00m** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
got an error now

**Comment by DoctorD1501** [comment]
Looks like this could be tough to track down - I may be able to free up some objects after the movie has written to disk completely instead of waiting until every single movie is written, but at some point, if you scrape too many movies in one batch, they won't be able to fit in the max heap size the program is currently running in (256MB for most). Another possibility is I can increase the max heap size the program runs in, although this will only delay the issue until you scrape a higher number of movies.

Short term solution is try not to scrape too many movies at once until I can figure something out.

**Comment by shad00m** [comment]
I have (and probably most others as well) have a lot of spare ram that is unused. Maybe a setting that lets us set the heap size would be acceptable if you cannot figure out something "better"

**Comment by DoctorD1501** [comment]
I've uploaded a new beta to mediafire with a quick fix to just clear out the cache when it reaches a certain number of items. I was actually already doing this in one place, but forgot to add it in when I added a new method for the async image stuff. Can you try it out let me know if this is fixing things for you? Thanks.

Here is the link: http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

**Comment by shad00m** [comment]
it finished scraping 37 files but
the last ~15 files did not get their files written even though it appeared that it has finished writing
i scraped the 15 again and then it wrote the files properly.
Not sure if something is wrong with the scraping or writing process

**Comment by DoctorD1501** [comment]
Should be fixed now in e9ee873692bd6350d02eca85bf445c110fb60784 or at least greatly improved. Let me know if you still notice any issues.

Thanks for your patience - it took me a while to track this down.
