### ISSUE TITLE
Feature Request: Option to not save <thumb> inside .NFO

### ISSUE THREAD

**Issue by PrSinister** [DoctorD1501/JAVMovieScraper#122]
The thumb linked in the nfo for the poster is not cropped and is therefore unwanted. The cropped file is already saved in the folder.

The fanart when automatically scraping is the full jacket and i don't want this as my fanart so i rename it to jacket.jpg ... so i don't want the nfo to contain the fanart that is not wanted.

**Comment by DoctorD1501** [comment]
Hey PrSinister,

I've added this preference setting in the most recent commit. It will be rolled in with the other changes when I make a new release. In the mean time, you can grab the newest development build here to get the version that has this feature:

http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

The new preference is under the "Preferences -> File Creation -> Write <thumb> tags for poster and fanart into file" checkbox.

-DoctorD
