### ISSUE TITLE
Cannot Edit NFO File and Save

### ISSUE THREAD

**Issue by PrSinister** [DoctorD1501/JAVMovieScraper#128]
When modifying anything in the NFO, changes are not saved. Editing a field and then writing file to disk just reverts to the original scraped data

(v0.2.15-alpha)

**Comment by DoctorD1501** [comment]
I'm not seeing this issue. If you enable the message console, do you see any errors? Is the file write protected? Does your user have access to modify the file in the OS?

**Comment by PrSinister** [comment]
I am an administrator and have full rights... The console just shows that it is writing all the previous data. I do not use the rename feature.

Attached are screenshots of my settings...
![2016-03-28 1](https://cloud.githubusercontent.com/assets/247870/14095502/09dd2c68-f52f-11e5-948c-82f09c0ec167.jpg)
![2016-03-28 2](https://cloud.githubusercontent.com/assets/247870/14095507/16be14ec-f52f-11e5-9a1a-a03f3d4303b0.png)

**Comment by DoctorD1501** [comment]
Can you post the full console output of doing the following? I'm still not able to recreate the problem, but maybe I'll see something interesting in the console.

1) Open the program
2) select your file
3) scrape the file
4) write the file to disk
5) try to edit a field
6) write the file to disk again

**Comment by PrSinister** [comment]
Weird enough, after Windows updates and reboot, it started working.

Sorry about that.
