### ISSUE TITLE
Cannot scrape from DMM.co.jp

### ISSUE THREAD

**Issue by mcn5150** [DoctorD1501/JAVMovieScraper#129]
Cannot scrape most of JAVs from DMM.co.jp.
The output panel is showing an "Illegal character in path at index 0" when trying to access the website of most JAVs. In some of them it still works (e.g. IDOL-083, PCM-048) but in the majority it doesn't work.
In some cases it just shows Movie scraped=null.
Scraping data in English and Japanese is still working perfectly on v1.31 and below.

**Comment by DoctorD1501** [comment]
Fixed in 99f004d2b3e08b9d642047449cdfa563edfe493f
