### ISSUE TITLE
New commits

### ISSUE THREAD

**Issue by oriongrimm** [DoctorD1501/JAVMovieScraper#133]
Hello could you tell me how to compile a updated jar for the recent commits? I have little knowledge of java but I have tried importing it into eclipse and exporting it into a jar. A new release would be appreciated as well.

**Comment by DoctorD1501** [comment]
I just made a new release now so you should be able to use the new commits.

Assuming the build is compiling in eclipse for you, this is the process I use to make a build in eclipse:

1. Right click project, click "Export"
2. Select "Runnable JAR File" under "Java"
3. Library handling should be set to "Extract required libraries into generated JAR"
4. Launch configuration should be "Main - Start GUI - JAVMovieScraper"> if you don't have this configuration (I'm not sure if it transfers to github or is local to my machine, read below)
5. Select file location under export destination. The filename should end in .jar
6. Click finish.

Info on the launch configuration (create one in the run configurations screen):

Main - Start GUI:
Project: JAVMovieScraper
Main class: moviescraper.doctord.Main

**Comment by oriongrimm** [comment]
Thank you for this tool. I am a neat freak and a data hoarder. I have organized over 4TB of "files" with this tool. the current release is much quicker and more stable with larger batches.

**Comment by DoctorD1501** [comment]
Cool. I'm glad to hear the program is working better for you now and that you find the program useful. I don't always have as much time as I would like to make updates or fill all the feature requests people have, but I do prioritize serious bugs like scrapers that completely stop working. Just let know if you notice anything that goes wrong.

-DoctorD
