### ISSUE TITLE
submenu problem

### ISSUE THREAD

**Issue by grosso73** [DoctorD1501/JAVMovieScraper#137]
![submenu](https://cloud.githubusercontent.com/assets/19393311/15297292/90f44a7a-1b99-11e6-918a-50d9fabd032a.jpg)
New submenu not working at me...
What can be the problem ?

**Comment by DoctorD1501** [comment]
You need java 8 JDK installed. And the project needs to be set to use the java 8 as well. You're probably using java 7, which is why you can't use lambda expressions.

**Comment by grosso73** [comment]
Thank you, it's working now.
