### ISSUE TITLE
Issues with writing additional scraper

### ISSUE THREAD

**Issue by domxch** [DoctorD1501/JAVMovieScraper#139]
I'm trying to write a scraper for Arzon as it has some information for some rare titles that I haven't found elsewhere.
I've hit 2 issues:-
Arzon has an age check - I've managed to bypass this with the following:

Response res = Jsoup
                    .connect("https://www.arzon.jp")
                    .data("action", "adult_customer_agecheck", "agecheck", "1")
                    .method(Method.POST)
                    .timeout(1000*15)
                    .execute();

```
        Map<String, String> loginCookies = res.cookies();
```

This bypasses the age check and gets the session cookies.

Document doc = Jsoup.connect(searchString).userAgent("Mozilla").ignoreHttpErrors(true).timeout(SiteParsingProfile.CONNECTION_TIMEOUT_VALUE).cookies(loginCookies).get();

This then retrieves the page using the session cookies. This works but is a bit clunky...

The second issue is around retrieving the poster. Cookies aren't needed but the referer property needs to be set to the html page that contains the image. I've got this to work so far using the URLConnection object but haven't yet worked out where in the application I would need to make that change if the website returns a 403 error...

**Comment by DoctorD1501** [comment]
Looks like you're doing the cookies correctly. 

For the referer property, I think you can do it like how I do the translation which also required a referrer. Setting it even if you don't need it won't hurt, so you can just always set it for that scraper:

Document doc = Jsoup.connect(translationServicePostURL).**referrer("http://translate.google.com")**.userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0").timeout(SiteParsingProfile.CONNECTION_TIMEOUT_VALUE).post();

**Comment by Wizell** [comment]
Cleaning non bug necro-issue
