### ISSUE TITLE
the JAVMovieScraper2.23 cannot be used in Windows 7

### ISSUE THREAD

**Issue by ws01459293** [DoctorD1501/JAVMovieScraper#146]

**Comment by brunho** [comment]
and on Windows 10 ....

**Comment by DoctorD1501** [comment]
Delete AmalgamationSettings.json. Does that fix the problem?

**Comment by Darklyter** [comment]
Actually, make sure that you have the 64bit Java loaded.  Since Doc made the changes to the memory boost at the beginning it has failed to launch under 32bit.  (Just figured that out myself about an hour ago)

PS. DoctorD1501, THANK YOU!

**Comment by DoctorD1501** [comment]
Weird. I set the new default heap space to be 1024M, which _should_ work on 32bit java, but I didn't really test it there either. Darklyter - are you sure that is what fixed it and not deleting the AmalgamationSettings.json?

I _might_ be able to put in some extra checks to see if 32bit java is running if needed and go back to the old behavior, but honestly the program will work much better when doing a large batch scrape if more cache memory is available.

**Comment by Darklyter** [comment]
Positive.  I still have some phantom processes running in 32bit from the times I tried launching before installing the 64bit version.  I tried it from the command line with a -verbose and saw that it bombed out, though I don't have the error in the window now.  Once I installed the 64bit it worked fine.  No other changes.

**Comment by Darklyter** [comment]
As a matter of fact, I didn't default the amalgamation settings until I saw that javbus wasn't an option.  Defaulting them made it show up.

**Comment by DoctorD1501** [comment]
Alright, I'll download & install the 32bit version to see what is going on.

Thanks for the bug reports everyone.

**Comment by DoctorD1501** [comment]
People with 32bit java - can you guys download the newest dev build (v0.2.24-alpha) here:

http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

and see if it is now working for you?

**Comment by noisyscott** [comment]
I just tried v0.2.24-alpha on my Ubuntu 14.04.4 LTS box and got this error:

~/Applications/JAVMovieScraper-v0.2.24-alpha$ java -jar JAVMovieScraper.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: moviescraper/doctord/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Here's my java version:
$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by DoctorD1501** [comment]
noisyscott - You need java version 8. It looks like you have java version 7.

**Comment by noisyscott** [comment]
Thanks!  Updated and it's running fine now.  The JAVBus addtion is working great and is a welcome addition!

**Comment by DoctorD1501** [comment]
I'm going to close this issue. Please let me know in a new issue if anyone is still having a problem with 2.24.
