### ISSUE TITLE
[Feature Request] Add support for MGStage

### ISSUE THREAD

**Issue by oldpoem** [DoctorD1501/JAVMovieScraper#150]
I have some original series from MGStage (Mostly SIRO & GANA Series)  which is site exclusives.  Support from MGStage would be very much appreciated since none of title information is available on other sites.

**Comment by Mosney** [comment]
Also need! So why no one scraper support MGStage until now?

**Comment by Mosney** [comment]
@Wizell Please look here. Could any possible to add a scraper for [MGS](https://www.mgstage.com/) ?  I think there are more and more excellent jav contains from this site, so if possible, please keep an eye on this, thank you contribution!

**Comment by Wizell** [comment]
I don't mind adding this scraper but i need help. Please use the "request new scraper" issue template and help me with what you want to see in the scraper
