### ISSUE TITLE
Command line problem

### ISSUE THREAD

**Issue by grosso73** [DoctorD1501/JAVMovieScraper#153]
I tried to use command line as it was described, but it always starts the GUI.
Is it only at me ?

**Comment by DoctorD1501** [comment]
It seems to be working for me. What is the complete command line option you are using?

**Comment by grosso73** [comment]
For example as in the examples section written : java -jar JAVMovieScraper.jar -scrape data18webcontent "C:\myfile1.mp4"

**Comment by DoctorD1501** [comment]
OK, and do you get an error when you try it? If so, what is the error? I just tried that exact option (obviously changing the path [the part that says C:\myfile1.mp4] to a file that exists on my computer) and it scraped and wrote some files to the disk

**Comment by Wizell** [comment]
No update since a long time and this does not look like a bug. Closing. Please reopen an issue if this is really not working.
