### ISSUE TITLE
Data 18 web content scraper only getting ID

### ISSUE THREAD

**Issue by Keysersose12** [DoctorD1501/JAVMovieScraper#154]
The Data 18 web content scraper worked for first search but for every other search it just returns the ID with no other metadata.

**Comment by Still34** [comment]
Same here.

**Comment by pr0nNDal** [comment]
Seeing the same issue.

**Comment by Darklyter** [comment]
When that happens, open IE and go to the URL that displays in the Console Window in the scraper.  For me it seems that possibly Data18 is considering you a robot and blocking the query.  When it happens to me I get a "Security Check" prompt, and after I click through get the page and it unlocks scraping again for a while.

However that being said, images aren't working for Web content from there right now, at least for me.  :-)

**Comment by syaofox** [comment]
Strip Please

**Comment by m0uthless** [comment]
@Darklyter now works with your method but still no image... any solution?

**Comment by Darklyter** [comment]
It's sort of hit or miss for me, especially with web clips.  One day it will work fine, the next it will pull all of the metadata except thumbnails.  Doesn't seem to be any rhyme or reason.

**Comment by giantsfan006** [comment]
@Darklyter tried your workaround yesterday and it worked (yay!)

tried it today and it did not (boo...)

my OCD is killing me...

**Comment by insickin** [comment]
With the given solution I get all of the information except for the poster and fan-art

**Comment by yellowhunt** [comment]
same here

**Comment by yellowhunt** [comment]
I think I've found a solution. Let's see if it keeps working.
1) add ghostery browser extension
2) delete data 18 cookies
3) scrap the data, click on preview
4) pass the security 
5) scrap again, and you'll have the details.

**Comment by DoctorD1501** [comment]
I added in code to automatically get through the security page in the newest release as well as Darklyter's fixes. Please let me know if you all notice any issues.
