### ISSUE TITLE
Google Translate 403

### ISSUE THREAD

**Issue by Lord-Simon** [DoctorD1501/JAVMovieScraper#156]
For some time now the Scraper has been throwing the "org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=http://translate.google.com/?sl=ja&tl=en&js=n&prev=_t&hl=en&ie=utf-8&eotf=1&text=%E8%BE%B1%E3%82%81&file=" error.

**Comment by Still34** [comment]
Same here, been seeing 403 errors.

**Comment by DoctorD1501** [comment]
I've pulled in this fix now. New dev release will be on mediafire until the other things get fixed as well.

Thanks Lord-Simon!
