### ISSUE TITLE
Another Data18 Issue with Thumbnails

### ISSUE THREAD

**Issue by Darklyter** [DoctorD1501/JAVMovieScraper#158]
I don't know if DoctorD is still active on this project or not, but I REALLY hope so!

Just in case I wanted to let you know something I've found, in case you hadn't already... and all of this is from someone who played around with your code, but doesn't have a clue how to actually write Java code to fix the problem:

A lot of times for movies or webclips it will pull up empty boxes for all of the thumbnails with the possible exception of the back cover.  Sometimes not though, and it works just fine.

From what I can tell Data18 has changed their format for newer titles to that the gallery contentID changes when you go into the gallery.

What I mean by that is this:

Let's use the movie A-Bombs #2 (just because that's what I was testing with...  http://www.data18.com/movies/1133902)

You scrape all of the information just fine, and then pull out the contentID for the various galleries:

Example: `SceneContentLink = <a href="http://www.data18.com/content/6124315" title="Scene 1: Suzan Motta in A-bombs #2"><img src="http://img.data18.com/25/133902/124315/hor5.jpg" class="yborder" alt="scene" /></a>`

You then pull up the gallery page and scrape the images by going through the viewer page with that contentID:

`currentViewerPage = http://www.data18.com/viewer/6124315/01`
`currentViewerPage = http://www.data18.com/viewer/6124315/02`
`currentViewerPage = http://www.data18.com/viewer/6124315/03`

However if you actually go to those links you'll pull up info (missing in this case) for "The First and the Last (2008)"

Instead Data18 has changed the URL to a different contentID than what was passed to the original viewer (from the gallery page at `http://www.data18.com/content/6124315`) and the _ACTUAL_ content id for these images is now 7124315:

`<a href="http://www.data18.com/viewer/7124315/01" rel="nofollow"><img src="http://img.data18.com/25/133902/124315/th/01.jpg" alt="image 1" style="border: 13px solid #EEEEEE;" /></a>`
`</div>&nbsp;<div style="float: left; margin-left: 8px; margin-top: 7px;">`
`<a href="http://www.data18.com/viewer/7124315/02" rel="nofollow"><img src="http://img.data18.com/25/133902/124315/th/02.jpg" alt="image 2" style="border: 13px solid #EEEEEE;" /></a>`
`</div>&nbsp;<div style="float: left; margin-left: 8px; margin-top: 7px;">`
`<a href="http://www.data18.com/viewer/7124315/03" rel="nofollow"><img src="http://img.data18.com/25/133902/124315/th/03.jpg" alt="image 3" style="border: 13px solid #EEEEEE;" /></a>`
`</div><div style="clear: both;"></div><p style="text-align: center;">`

So essentially you just need another step in there to scrape the new contentID from the actual gallery page for the pictures instead of just using the one that was given to you on the main title page.

So while `http://www.data18.com/viewer/6124315/01` doesn't work, `http://www.data18.com/viewer/7124315/01` does.

Hopefully that makes sense...  and man, I wish I knew how to do it myself.

**Comment by Darklyter** [comment]
And if this should have been a private message, I apologize...  but just in case you're not working on this project anymore maybe someone else can bugfix it real quick.  :-)

Btw, in case you do get this thanks for such an incredibly useful tool!

**Comment by Darklyter** [comment]
Well, still have the issue but different now.  I hacked together a quick fix for the contentID, however it's still failing to pull the images from the server.  If I open a link in Chrome, for example `http://74.50.117.49/pics/925/150959/28.jpg` where I browsed Data18 it works fine.  But in JavScraper, or if I just open IE or Firefox and pull the same link it fails with a permission denied.    ("You don't have permission to access /pics/925/150959/28.jpg on this server.")

If I browse in Firefox to the same image in the Viewer (`http://www.data18.com/viewer/5451155/03`) I can then pull it up via the direct IP address.  Is it possible to pull the image from the initial dump of the viewer page without pulling it directly as an additional get?  Or possibly store cookies, or whatever the heck the site is using to block access unless you've been to the Viewer page.

**Comment by Darklyter** [comment]
Ok, here's a quick and very hacked together fix for the problem, as well as fixing the problem of duplicating the thumbnail results sometimes.  This seems to have fixed it for me, however if you get blank results it seems to happen due to being 'blocked' by Data18.  The same code gave me empty results last night, this morning worked fine once it had time to expire the block.

I'm just including the entire scrapeExtraFanart function since I _think_ I only added bits to the middle, but I'm not sure.

I don't know if anyone else has had this problem or not, but I know I did.  ;-)


`import java.util.HashSet;`


`	public Thumb[] scrapeExtraFanart() {
		hasRunScrapeExtraFanart = true;
		if(scrapedExtraFanart != null)
		{
			return scrapedExtraFanart;
		}
		//find split scene links from a full movie
		Elements sceneContentLinks = document.select("div[onmouseout]:matches(Scene \\d\\d?)");
		ArrayList<String> contentLinks = new ArrayList<>();
		ArrayList<Thumb> extraFanart = new ArrayList<>();
		if(sceneContentLinks != null)
		{
			//get just the id from url of the content
			for(Element sceneContentLink : sceneContentLinks)
			{
				Element linkElement = sceneContentLink.select("a[href*=/content/").first();
				if(linkElement != null)
					{
					String linkElementURL = linkElement.attr("href");
					if(linkElementURL.contains("/"))
					{
						String contentID = linkElementURL.substring(linkElementURL.lastIndexOf("/")+1,linkElementURL.length());
						contentLinks.add(contentID);
					}
				}
			}
		}

                // Checking for changed and/or different contentIDs from the main/root item and building a new array
                ArrayList<String> galleryLinks = new ArrayList<>();
		for(String myID : contentLinks)
		{
                    String currentGalleryURL = "http://www.data18.com/content/" + myID;
                    try {

                            Document galleryDocument = Jsoup.connect(currentGalleryURL).timeout(SiteParsingProfile.CONNECTION_TIMEOUT_VALUE).userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0").get();
                            if(galleryDocument!= null)
                            {                    
                                Elements galleryElement = galleryDocument.select("div a[href*=/viewer/]");
                                Element linkElement = galleryElement.select("a[href*=/viewer/").first();
                                if(linkElement != null)
                                    {
                                    String linkElementURL = linkElement.attr("href");
                                    if(linkElementURL.contains("/"))
                                    {
                                         String [] parts = linkElementURL.split("/");
                                         galleryLinks.add(parts[4]);
                                    }
                                }
                            }
                    } catch (IOException e) {
                            e.printStackTrace();
                            //continue; 
                    }
                }                
                
                // Results would be duplicated due to "Scene 1: xxxxxxxx" as well as "scene 1" later.  
                // Just removing those to get a clean list of galleries
                ArrayList<String> resultList = new ArrayList<>();
                HashSet<String> set = new HashSet<>();
                for (String link : galleryLinks){
                    if (!set.contains(link)){
                        resultList.add(link);
                        set.add(link);
                    }
                }
                

		//for each id, go to the viewer page for that ID
		//for(String contentID : contentLinks)
		for(String contentID : resultList)
		{
			//int viewerPageNumber = 1;
			for(int viewerPageNumber = 1; viewerPageNumber <= 15; viewerPageNumber++)
			{
				String currentViewerPageURL = "http://www.data18.com/viewer/" + contentID + "/" + String.format("%02d", viewerPageNumber);
				try {
					Document viewerDocument = Jsoup.connect(currentViewerPageURL).timeout(SiteParsingProfile.CONNECTION_TIMEOUT_VALUE).userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0").get();
					if(viewerDocument!= null)
					{
						Element imgElement = viewerDocument.select("div#post_view a[href*=/viewer/] img").first();
						if(imgElement != null)
						{
							String mainImageUrl = imgElement.attr("src");
							Thumb thumbToAdd = new Thumb(fixIPAddressOfData18(mainImageUrl));
							String previewURL = mainImageUrl.substring(0,mainImageUrl.length()-6) + "th8/" + mainImageUrl.substring(mainImageUrl.length()-6,mainImageUrl.length());
							if(fileExistsAtURL(previewURL))
								thumbToAdd.setPreviewURL(new URL(fixIPAddressOfData18(previewURL)));
							extraFanart.add(thumbToAdd);
						}
					}
					
				} catch (IOException e) {
					e.printStackTrace();
					//continue;
			}
			
			}
		}
		scrapedExtraFanart = extraFanart.toArray(new Thumb[extraFanart.size()]);
		return scrapedExtraFanart;
	}
`

**Comment by yellowhunt** [comment]
wow you are great 👍, I wish I knew how to put this code in the scraper. :(

**Comment by Darklyter** [comment]
Honestly that's the first bit of java I've ever hacked together.  It was working earlier today, however now I'm back to blank images except for the back cover.  Getting the permission failure.  Wish I could figure out a way around that, but I don't know if it's a cookie problem or what.

I'm hoping that DoctorD or one of the other devs can clean it up and put it in place though, since it seems to work better (when it is permitted)

**Comment by Darklyter** [comment]
Ok, so two freaking days and I finally figured it out.  Apparently Data18 is requiring a Referer in the connection header at what seems to be high traffic times of day.  (For me it started about 7:00pm EST).

I've hacked together more code that seems to get around the problem.  (I pass the value of the 'Viewer' gallery url over to the Thumb class and use that in AsyncImage to send to the server)

If any developers are out there reading this, can you take a look at my fork?  https://github.com/Darklyter/JAVMovieScraper  I would do a pull request but I have 1) No idea how and 2) never having written Java before I'm afraid I might have screwed up something that I don't know about.

Also no laughing at all of the changes when I was setting the repository/project up!  Never done that either.  ;-)

**Comment by DoctorD1501** [comment]
The newest release has these changes plus some additional referrer logic to make stuff download.
