### ISSUE TITLE
Plot fails 95% of the time

### ISSUE THREAD

**Issue by PrSinister** [DoctorD1501/JAVMovieScraper#159]
The scraping of the plot for JAV Censored seems to be broken for a few months now. Any update coming or is this project abandoned?

**Comment by Darklyter** [comment]
I hadn't thought about it until you mentioned it, but the same here.  However I went and looked on JavLibrary, JavBus, ActionJav, R18 and JavZoo (AVmoo) and I'm actually not seeing plots on the movies listed there.  I might just be missing them, but it seems that it's not the scraper, but there's no plot on the sites themselves any more.

**Comment by DoctorD1501** [comment]
Plot should be coming in now thanks to Lord-Simon's google translate fix.
