### ISSUE TITLE
write of .nfo file fails, if <thumb> tag is empty

### ISSUE THREAD

**Issue by nafets1** [DoctorD1501/JAVMovieScraper#162]
if the <thumb></thumb> tags are in the info file, but empty
(due to the use of another nfo editor, or manual editing)
the WriteFileData button does NOT rewrite info file
running under OS X

if the tag is removed completly, everything works !

**Comment by DoctorD1501** [comment]
Fixed in latest commit. You can grab the dev build from mediafire to get this fix.
