### ISSUE TITLE
1pondo scraper Unable to get video information

### ISSUE THREAD

**Issue by sunnyruin** [DoctorD1501/JAVMovieScraper#175]
1pondo scraper Unable to get video information，i found a way could get some information，like the link“http://www.1pondo.tv/dyn/ren/movie_details/movie_id/042815_069.json”，maybe could give u some help

**Comment by DoctorD1501** [comment]
You need to have the ID of the movie as the last word of your file name. For example,  you file could be called:

"Blah blah blah some movie - 042815_069.mp4" and if you select the 1Pondo scraper and hit scrape, it should work. It does for me when I try it.
