### ISSUE TITLE
Data 18 Web Not pulling poster/fanart

### ISSUE THREAD

**Issue by hstegeman** [DoctorD1501/JAVMovieScraper#176]
Since a few days I am making use of JAVMovieScraper. It's working very well except pulling posters/fanart from edited nfo's.

Example:

I am scraping Suicide Squad XXX An Axel Braun Parody - SCENE 1. with Asa Akira.

Gui Initialized
Movie Size: 1
currentItemSource = Data18 Web Content with disabled = false
F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1.mp4
currentItemSource = Default Data Item Source with disabled = false
Prompt user for search results for Data18 Web Content
fileBaseName = Suicide Squad XXX An Axel Braun Parody - SCENE 1
searchString = http://www.data18.com/search/?k=Suicide+Squad+XXX+An+Axel+Braun+Parody+-+SCENE+1&t=0
fileBaseName = Suicide Squad XXX An Axel Braun Parody - SCENE 1
Scraping this webpage for movie: http://www.data18.com/content/386380
Title by Property: Asa Akira in Suicide Squad XXX: An Axel Braun Parody
Original Title by Property: Asa Akira in Suicide Squad XXX: An Axel Braun Parody - data18.com
Using full movie's plot instead of scene's plot (which wasn't found): Axel Braun strikes back! For his fourth Wicked Comix title, the legendary Adult film director takes on the most anticipated superhero movie of the summer with another hi-budget sexy spoof. Featuring a stellar cast lead by Kleio Valentien, reprising her award-winning role as Harley Quinn, megastar Asa Akira as Katana, Anna Bell Peaks in a star-making role as Killer Frost, and ABP contract girl Riley Steele returning as Enchantress, Suicide Squad XXX: An Axel Braun Parody delivers a clever story, steamy hot sex scenes, and a mind-blowing performance by Best Actor winner Tommy Pistol as The Joker.
Official Poster: Thumb [thumbURL=http://media.data18.com/scenes/3/4/86380-asa-akira-lexington-steele-suicide-squad-xxx-an-axel-braun-parody.jpg" source="Default Data Item Source"]
Starring: Asa Akira
Starring: Lexington Steele
Scraping complete of siteScraper = Data18 Web Content
Skipping amalgamation process as there is only one movie
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/06.jpg" source="Data18 Web Content"]
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/01.jpg" source="Data18 Web Content"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Data18 Web Content"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file

No problem untill now. But when I close JAVMovieScraper and try to select an other poster, I am getting an error message.

after restarting JAVMovieScraper

Gui Initialized
Movie Size: 1
Movie Size: 1
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/15.jpg" source="Default Data Item Source"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Default Data Item Source"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
Error: Server returned HTTP response code: 403 for URL: http://74.50.117.48/138/2594/86380/15.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Error: Server returned HTTP response code: 403 for URL: http://74.50.117.48/138/2594/86380/01.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file

Can this problem be solved?

**Comment by DoctorD1501** [comment]
I'm not getting the same error when I recreate your steps and things seem to be working ok for me on my end. That said, I have noticed some stuff like that that I tried to solve at one point by putting in a referrer in the URL. It's possible it's not working correctly for you for some reason.

If you just paste:

http://74.50.117.48/138/2594/86380/15.jpg into your browser's URL box and hit enter, do you get an error or does the image load OK? 

The error that it's showing is 403, which is a permission denied when trying to access a resource on a webserver.

**Comment by hstegeman** [comment]
If I fill in http://74.50.117.48/138/2594/86380/15.jpg in my browser, I can see the poster that I did select.
I thought that fixIPAddressOfData18 did solve this problem.

stringWithIPAdressReplaced = stringWithIPAdressReplaced.replaceFirst("78.110.165.210", "74.50.117.48");

**Comment by DoctorD1501** [comment]
Are you editing the nfo in JavMovieScraper or another program? Can you post a before and after nfo file?

**Comment by hstegeman** [comment]
I am making use of JavMovieScraper for editing.
My windows computer did just get an update, after the update I couldn't reproduce my error for a while. But after a while the error did come back again.

The order of the thumbs in the nfo is only changing.

Before.
  <thumb>http://74.50.117.48/138/2594/86380/06.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/01.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/02.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/03.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/04.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/05.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/07.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/08.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/09.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/10.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/11.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/12.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/13.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/14.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/15.jpg</thumb>
  <thumb>http://media.data18.com/scenes/3/4/86380-asa-akira-lexington-steele-suicide-squad-xxx-an-axel-braun-parody.jpg</thumb>

After.
  <thumb>http://74.50.117.48/138/2594/86380/14.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/06.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/15.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/01.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/02.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/03.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/04.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/05.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/07.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/08.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/09.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/10.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/11.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/12.jpg</thumb>
  <thumb>http://74.50.117.48/138/2594/86380/13.jpg</thumb>
  <thumb>http://media.data18.com/scenes/3/4/86380-asa-akira-lexington-steele-suicide-squad-xxx-an-axel-braun-parody.jpg</thumb>

Example:
I scrape the scene, after writing the file data I am editing the file until it gives an error. I didn't close JavMovieScraper this time.

http://74.50.117.48/138/2594/86380/15.jpg (no problem in browser)
http://74.50.117.48/138/2594/86380/14.jpg (forbidden in browser, no error while editing nfo?)
http://74.50.117.48/138/2594/86380/06.jpg (forbidden in browser, error writing the filedata, no error while scraping the first time?)
http://74.50.117.48/138/2594/86380/14.jpg (forbidden in browser, error while editing nfo?)
http://74.50.117.48/138/2594/86380/01.jpg (no problem in browser, but error writing the filedata)

Scraping Suicide Squad XXX An Axel Braun Parody - SCENE 4
By mistake I did also select the previous time scene 4 instead of scene 1.

Gui Initialized
Movie Size: 1
currentItemSource = Data18 Web Content with disabled = false
F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1.mp4
currentItemSource = Default Data Item Source with disabled = false
Prompt user for search results for Data18 Web Content
fileBaseName = Suicide Squad XXX An Axel Braun Parody - SCENE 1
searchString = http://www.data18.com/search/?k=Suicide+Squad+XXX+An+Axel+Braun+Parody+-+SCENE+1&t=0
fileBaseName = Suicide Squad XXX An Axel Braun Parody - SCENE 1
Scraping this webpage for movie: http://www.data18.com/content/386380
Title by Property: Asa Akira in Suicide Squad XXX: An Axel Braun Parody
Original Title by Property: Asa Akira in Suicide Squad XXX: An Axel Braun Parody - data18.com
Using full movie's plot instead of scene's plot (which wasn't found): Axel Braun strikes back! For his fourth Wicked Comix title, the legendary Adult film director takes on the most anticipated superhero movie of the summer with another hi-budget sexy spoof. Featuring a stellar cast lead by Kleio Valentien, reprising her award-winning role as Harley Quinn, megastar Asa Akira as Katana, Anna Bell Peaks in a star-making role as Killer Frost, and ABP contract girl Riley Steele returning as Enchantress, Suicide Squad XXX: An Axel Braun Parody delivers a clever story, steamy hot sex scenes, and a mind-blowing performance by Best Actor winner Tommy Pistol as The Joker.
Official Poster: Thumb [thumbURL=http://media.data18.com/scenes/3/4/86380-asa-akira-lexington-steele-suicide-squad-xxx-an-axel-braun-parody.jpg" source="Default Data Item Source"]
Starring: Asa Akira
Starring: Lexington Steele
Scraping complete of siteScraper = Data18 Web Content
Skipping amalgamation process as there is only one movie
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/06.jpg" source="Data18 Web Content"]
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/01.jpg" source="Data18 Web Content"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Data18 Web Content"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/15.jpg" source="Data18 Web Content"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Data18 Web Content"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/14.jpg" source="Data18 Web Content"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Data18 Web Content"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file
Movie Size: 1
Movie Size: 1
Movie Size: 1
Movie Size: 1
Movie Size: 1
Movie Size: 1
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/06.jpg" source="Default Data Item Source"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Default Data Item Source"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
Error: Server returned HTTP response code: 403 for URL: http://74.50.117.48/138/2594/86380/06.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Error: Server returned HTTP response code: 403 for URL: http://74.50.117.48/138/2594/86380/01.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file
returning option picked from panel = Thumb [thumbURL=http://74.50.117.48/138/2594/86380/14.jpg" source="Default Data Item Source"]
Movie Size: 1
Writing this movie to file: Title [title="Asa Akira in Suicide Squad XXX: An Axel Braun Parody" source="Default Data Item Source"]
Writing poster file from nfo: F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-poster.jpg
Error: Server returned HTTP response code: 403 for URL: http://74.50.117.48/138/2594/86380/14.jpg
saving out first fanart to F:\TEMP\Suicide Squad XXX An Axel Braun Parody - SCENE 1-fanart.jpg
Error: Server returned HTTP response code: 403 for URL: http://74.50.117.48/138/2594/86380/01.jpg
Writing .actor images into F:\TEMP
Finished writing a movie file

But when I delete the nfo's and art files and scrape the scene file new again. I don't get an error message when writing the filedata the first time.

**Comment by hstegeman** [comment]
Perhaps not related, but I want to mention. In the past I did help editing a imdb indexer for Istream.
The problem was that the source of the websites did change depending on the country you live in.
That problem could solved by adding a variable that you want to make use of the US website.

        if self.Settings().get_setting('en_us')=='true':
            content = net.http_GET(new_url,{'Accept-Language':'en-US'}).content
        else:
            content = net.http_GET(new_url).content

If I look in the html code I can see the next line.
<!DOCTYPE html>          
<html lang="en"> 

I think in the VS the code will be:

<!DOCTYPE html>          
<html lang="en-US">

The source of the website could be different by Country.

**Comment by pibi73** [comment]
Hi,

i have your same problem.
Picture http://78.110.165.210/pics/1270/151884/63.jpg ERROR
Picture http://209.133.209.51/pics/1270/151884/63.jpg all it's ok.

any idea how to resolve the problem ?
Thanks a lot

**Comment by Wizell** [comment]
Is this issue still current on v0.3.2 ?

**Comment by Wizell** [comment]
Closing. If there is another issue, please create a new issue
