### ISSUE TITLE
Data 18 Web Not scaping any data

### ISSUE THREAD

**Issue by hstegeman** [DoctorD1501/JAVMovieScraper#177]
Some web scenes in data 18 are not scraping any data.

The source for all scenes start with http://www.data18.com/content/[range of numbers 6 or 7]
If the website does have a range of 7 numbers, the website won't get scraped.

A few examples:

Movie Size: 1
currentItemSource = Data18 Web Content with disabled = false
currentItemSource = Default Data Item Source with disabled = false
F:\TEMP\Evil Group Sex - SCENE 1.mp4
Prompting the user for a url for Data18 Web Content
Prompt user for search results for Data18 Web Content
fileBaseName = Evil Group Sex - SCENE 1
searchString = http://www.data18.com/search/?k=Evil+Group+Sex+-+SCENE+1&t=0
fileBaseName = Evil Group Sex - SCENE 1
Scraping this webpage for movie: http://www.data18.com/content/5379382
Scraping complete of siteScraper = Data18 Web Content

currentItemSource = Data18 Web Content with disabled = false
currentItemSource = Default Data Item Source with disabled = false
F:\TEMP\Lexs Anal Champions - SCENE 1.mp4
Prompting the user for a url for Data18 Web Content
Prompt user for search results for Data18 Web Content
fileBaseName = Lexs Anal Champions - SCENE 1
searchString = http://www.data18.com/search/?k=Lexs+Anal+Champions+-+SCENE+1&t=0
fileBaseName = Lexs Anal Champions - SCENE 1
Scraping this webpage for movie: http://www.data18.com/content/5365084
Scraping complete of siteScraper = Data18 Web Content

currentItemSource = Data18 Web Content with disabled = false
currentItemSource = Default Data Item Source with disabled = false
F:\TEMP\Roccos Best Fresh Teens - SCENE 1.mp4
Prompting the user for a url for Data18 Web Content
fileBaseName = Roccos Best Fresh Teens - SCENE 1
Scraping this webpage for movie: http://www.data18.com/content/5383596
Scraping complete of siteScraper = Data18 Web Content

currentItemSource = Data18 Web Content with disabled = false
currentItemSource = Default Data Item Source with disabled = false
F:\TEMP\Evil Group Sex - SCENE 4.mp4
Prompting the user for a url for Data18 Web Content
fileBaseName = Evil Group Sex - SCENE 4
Scraping this webpage for movie: http://www.data18.com/content/5379385
Scraping complete of siteScraper = Data18 Web Content

Edit:
A few hours ago I have been flagged about the logs that I did send.
I don't want to get banned, so I think this is my last respond online.
For further contact you can contact me by mail.

**Comment by Wizell** [comment]
Should be fixed by v0.3.2
