### ISSUE TITLE
data18 Fanart/poster problem

### ISSUE THREAD

**Issue by pibi73** [DoctorD1501/JAVMovieScraper#180]
hi guys, 

anyone else have problem to download fanart and poster from data18 Web content ?
all the pictures are grey/null .

for example, in the log i recive this error 
Error: http://74.50.117.48/222/3014/87542/01.jpg

but if i change the address to : http://http://209.133.209.51/222/3014/87542/01.jpg
i have found this new ip with the F12 option on chrome .
Any idea how to resolve the problem ?
Best regards.
thanks

**Comment by Wizell** [comment]
Is this still an issue with v0.3.2 ?

**Comment by Wizell** [comment]
Closing. If there is another issue, please create a new issue
