### ISSUE TITLE
programs constantly hangs

### ISSUE THREAD

**Issue by alejo82** [DoctorD1501/JAVMovieScraper#182]
Usually the program hangs causing all the data lost of the movies scraped.
This is very frustrating when scraping lot of movies because I have to start again and again.
 
Could be a way to implement if the program hangs save/write the file data of the movies scraped until that moment? 
or if the program hangs in one movie pass it to the next one in order to continue the scraping?
thank you.

**Comment by Wizell** [comment]
I can not reproduce this behavior on current version. Please test again and open a new issue if the problem is still present.
