### ISSUE TITLE
program hangs and crash

### ISSUE THREAD

**Issue by alejo82** [DoctorD1501/JAVMovieScraper#183]
kernel[0]: process java[64526] caught causing excessive wakeups. Observed wakeups rate (per sec): 150; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 331315

ReportCrash[71393]: Invoking spindump for pid=64526 wakeups_rate=150 duration=300 because of excessive wakeups

I found a developer that had this problem and how he solved it, the link is:
https://forum.xojo.com/27811-my-app-is-caught-causing-excessive-wakeups/0

**Comment by Wizell** [comment]
Can you give me more details like:
 - which version of java
 - which os and which version
 - can you reproduce the bug with the latest version

**Comment by Wizell** [comment]
No news since a long time. If the problem is still present please reopen an issue with requested details
