### ISSUE TITLE
Add manually cover, fanart

### ISSUE THREAD

**Issue by alexsaesee** [DoctorD1501/JAVMovieScraper#193]
Like I add manually an actor/actress and link an image, the possibility of adding manually a poster and fanart on a movie/video will be great.

A lot of videos aren't listed on scrapers/websites and need manual process.

**Comment by tehwateva** [comment]
You can already manually add a poster by using renaming the photo as filename-fanart.jpg and filename-cover.jpg and the scraper will pick it up automatically.

**Comment by alexsaesee** [comment]
Thank you for the precision, will try it.
