### ISSUE TITLE
Project maintenance and evolution

### ISSUE THREAD

**Issue by Wizell** [DoctorD1501/JAVMovieScraper#203]
From the facts that there is no commit on the repository since december 2016/12/14 and the differents pull requests have not been replied/rejected/accepted.

An unofficial maintenance repository can be found at https://github.com/Wizell/JAVMovieScraper until @DoctorD1501 is able to work again on the project.

Issues may be reported [here](https://github.com/Wizell/JAVMovieScraper/issues) (Please, only report issues for the lastest build available on the [unofficial repository](https://github.com/Wizell/JAVMovieScraper/releases))

**Comment by Wizell** [comment]
The current release on this repository release contains the following changes:
 * fixes all the tests (and parsing)
 * remove obsolete 1000giri website 
 * Add travis integration
 * Replace current build system by gradle

**Comment by alejo82** [comment]
Wizell, thank you much. 
Keep up the good work!

**Comment by DoctorD1501** [comment]
@Wizell 

Thanks so much for keeping the project up to date. I've been busy with other things and have not had the motivation to work on this project at all. I've made you an admin of this project so you can merge pull requests, etc. If you would prefer your own fork to be the main one that continues forward, that is OK too.

Thanks,
DoctorD1501

**Comment by Wizell** [comment]
@DoctorD1501 
Good to see you back. I think it would be much better not to keep my fork but rather to keep working on the main repository.

So far, what i'm working on when i got time for JavMovieScraper is a rework of amalgamation settings and some kind of interface based scraper detection which might allow easier scraper developpement (hopefully)

If it does sound fine with you i will work on it in branches on the main repository.

I also wrote a small info text with gradle instruction and descriptions of the services i registered on (like travis), If you are ok with those you might register on them to allow test and analysis of the repository

**Comment by Wizell** [comment]
@DoctorD1501 

I'm still not so familiar with github, but it seems that i cannot build new releases, handle issues (like add labels and so on).

**Comment by DoctorD1501** [comment]
@Wizell - Yeah feel free to remove the fork and keep this one as the main repo once you get going.

Are you sure? According to this: https://help.github.com/articles/permission-levels-for-a-user-account-repository/ you should be able to do things like make releases.

**Comment by Wizell** [comment]
@DoctorD1501 It's all ok. My bad, i didn't follow the link in the mail...

Everything seems to work fine. I just created a release from the current master branch state.

So developpements are back in this repository.
