### ISSUE TITLE
Comand Line Scraping ... error

### ISSUE THREAD

**Issue by marcelhehle** [DoctorD1501/JAVMovieScraper#210]
Hi

I'm trying to run JAVMovieScraper on the comand line and get this error:

[plex@pms JAVMovieScraper]$ java -jar JAVMovieScraper.jar -scrape data18 12\ Hungarian\ Teens\ \(2009\).mkv 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/home/plex/JAVMovieScraper/JAVMovieScraper.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Heap size is 3988.0M
Heap size good, continue to launch program
Scraping with scraper = data18
Filename =  12 Hungarian Teens (2009).mkv
Parsing with parsing profile = class moviescraper.doctord.controller.siteparsingprofile.specific.Data18MovieParsingProfile
Scraping this webpage for movie: http://www.data18.com/movies/1109635
Number of Thumbs: 77
Movie scraped asMovie [title=Title [title="12 Hungarian Teens" source="Data18Movie"], originalTitle=OriginalTitle [originalTitle="" source="Data18Movie"], sortTitle=SortTitle [sortTitle="" source="Data18Movie"], set=Set [set="" source="Data18Movie"], rating=Rating [maxRating="0.0", rating=""  source="Data18Movie"], year=Year [year="2012" source="Data18Movie"], top250=Top250 [top250="" source="Data18Movie"], trailer = Trailer [trailer="" source="Data18Movie"], votes=Votes [votes="" source="Data18Movie"], outline=Outline [outline="" source="Data18Movie"], plot=Plot [plot="Hungary, the country of Goulash and Palinka! However, many European's know that the best porn comes from Budapest too. Sluts like Boroka Balls, Aletta Ocean, Alexa Diamond and Nesty have already put many cocks to the test. This time it will not be the heat of the saunas and steam rooms that will raise your temperature." source="Data18Movie"], tagline=Tagline [tagline="" source="Data18Movie"], studio=Studio [studio="Private" source="Data18Movie"]releaseDate=ReleaseDate [releasedate="2012-07-10" source="Data18Movie"], runtime=Runtime [runtime="" source="Data18Movie"], posters=[], fanart=[Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/01.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/02.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/03.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/04.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/05.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/06.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/07.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/08.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/09.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/10.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/11.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/11.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/12.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/13.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/14.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/15.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/16.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/17.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/18.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/19.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/20.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/21.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/32.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/33.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/34.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/35.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/36.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/37.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/38.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/39.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/40.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/41.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/42.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/44.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/45.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/46.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/47.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/48.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/49.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/50.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/51.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/52.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/53.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/54.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/56.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/57.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/58.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/59.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/60.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/61.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/62.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/63.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/64.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/65.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/66.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/67.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/68.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/69.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/70.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/71.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/72.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/73.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/74.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/75.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/76.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/77.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/78.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/79.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/80.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/81.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/82.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/83.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/84.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/85.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/86.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/87.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/88.jpg" source="Data18Movie"]], extrafanart = [Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/01.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/02.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/03.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/04.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/05.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/06.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/07.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/08.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/09.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/10.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/11.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/11.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/12.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/13.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/14.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/15.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/16.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/17.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/18.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/19.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/20.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/21.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/32.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/33.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/34.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/35.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/36.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/37.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/38.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/39.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/40.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/41.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/42.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/44.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/45.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/46.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/47.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/48.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/49.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/50.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/51.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/52.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/53.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/54.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/56.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/57.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/58.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/59.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/60.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/61.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/62.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/63.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/64.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/65.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/66.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/67.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/68.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/69.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/70.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/71.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/72.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/73.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/74.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/75.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/76.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/77.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/78.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/79.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/80.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/81.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/82.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/83.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/84.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/85.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/86.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/87.jpg" source="Data18Movie"], Thumb [thumbURL=https://i5.datavimg.com/pics/457/109635/88.jpg" source="Data18Movie"]], mpaa=MPAARating [MPAARating="XXX" source="Data18Movie"], id=ID [id="" source="Data18Movie"], genres=[Genre [genre="7 Scenes" source="Data18Movie"], Genre [genre="European" source="Data18Movie"]], tags=[], actors=[Actor [role="null", Person [name="Aleksa Diamond", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/17614.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Aletta Ocean", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/12121.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Boroka Bolls", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/14328.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="David Perry", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/5186.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Dieter Von Stein", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/20125.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Eve Mendes", thumb=Thumb [thumbURL=https://i.datavimg.com/images/no_prev_60.gif" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="James Brossman", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/5564.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Lauro Giotto", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/15157.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Lauryn May", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/15165.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Liz Honey", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/1024.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Mike Angelo", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/17606.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Nesty", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/18082.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Regina Moon", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/1340.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Sabrina Sweet", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/1396.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Susanne Brend", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/1550.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Toni Ribas", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/17223.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Trisha Brill", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/11490.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Zafira", thumb=Thumb [thumbURL=https://i.datavimg.com/images/stars/120/18084.jpg" source="Default Data Item Source"]] source="Data18Movie"], Actor [role="null", Person [name="Regina", thumb=null] source="Data18Movie"], Actor [role="null", Person [name="Susanna Brend", thumb=null] source="Data18Movie"]], directors=[]]

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at moviescraper.doctord.Main.writeMovieToFile(Main.java:235)
	at moviescraper.doctord.Main.runScrape(Main.java:206)
	at moviescraper.doctord.Main.main(Main.java:116)
[plex@pms JAVMovieScraper]$ 

Any idea what I'm doing wrong? I need JAVMovieScraper to write nfo-Files because I have a fairly large library that I'll have to scrape via my own scripts.

**Comment by Wizell** [comment]
Can you confirm that you tried with v0.3.1 ?
If this is the case, the problem seems to be with the extra fanart folder.
Can you reproduce it if you scrape with just one movie ?

**Comment by marcelhehle** [comment]
Yes, it was v0.3.1

I'll try your fix this evening, when I'm back home.

**Comment by marcelhehle** [comment]
No, the error is still there, but now I get different line numbers in the error:

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at moviescraper.doctord.Main.writeMovieToFile(Main.java:217)
	at moviescraper.doctord.Main.runScrape(Main.java:188)
	at moviescraper.doctord.Main.main(Main.java:98)

**Comment by spldmanager** [comment]
This is because it needs absolute path !
