### ISSUE TITLE
Amalgamated using Data18 Web and iafd  togheter

### ISSUE THREAD

**Issue by slappy2** [DoctorD1501/JAVMovieScraper#211]
Hi,
I don't see how to use Amalgamated using Data18 Web and iafd  together.

**Comment by Wizell** [comment]
You can go in  Settings->Amalgamation Settings and then in the top combo box choose "American Adult DVD"

**Comment by slappy2** [comment]
Hi DoctorD,

1.       In the “American Adult DVD” there is no option for “Data18 WEB Content” but only the Data18Movie” wich is not working for web video. All the videos I want to scrape are in Data18 WEB Content and the actors from IAFD so I would like to use Amalgamation wich is actually impossible for DATA18 WEB. I have to edit manually one by one.


2.       Is there a scraper planned in the future to scrape video directly from LegalPorno.Com and able to took the images from Vipergirls.to or imagefap.com or google images for the poster and fanart ?


Thanks Very much for your help this is a powerfull tool !

[cid:image001.png@01D3AE44.A25BA300]

Steve
