### ISSUE TITLE
Help Request. Renaming syntax

### ISSUE THREAD

**Issue by Cromulent01** [DoctorD1501/JAVMovieScraper#217]
I feel like I'm doing something wrong but when I hit fille clean up it only relabels the folder and not the movie in the folder. What symbol do I need to add into the renaming settings?

Current settings 
file rename string : <TITLE> (<YEAR>)
 folder rename /move string : <BASEDIRECTORY><PATHSEPERATOR>

**Comment by Wizell** [comment]
I'm not familiar with this part of the code but i think you need to set "folder rename/move string" to "<BASEDIRECTORY><PATHSEPERATOR>". Can you try and report if it helps ?

**Comment by Wizell** [comment]
No news on this issue. Closing
