### ISSUE TITLE
FEATURE REQUEST - Up & Down Arrows To Adjust Actors List?

### ISSUE THREAD

**Issue by Cutters1982** [DoctorD1501/JAVMovieScraper#220]
Hi there

I would really like to see a feature added where you can adjust the order of the actors in a movie/scene, because often when its scraped they are not in the correct order (for example, I like to have Female A-Z, Male A-Z) rather than just an A-Z regardless of gender.

Please can this be added at some point? Removing & Adding is long winded, so left clicking on a name and pressing an up or down arrow to adjust the order would be awesome to have.

Cheers

**Comment by Wizell** [comment]
I opted for drag and drop reordering rather than keyboard based manipulation. 

This solution is implemented in master.
