### ISSUE TITLE
Data 18 not pulling Poster or Fanart

### ISSUE THREAD

**Issue by rod8687** [DoctorD1501/JAVMovieScraper#221]
Hi, the Data 18 Scraper is not pulling poster or fanarts, could you look into this?

Thanks a lot!

**Comment by Cutters1982** [comment]
It's working fine here, which scraper are you using, the Movie one or Web one?

What version of JAVMovieScraper are you using as well?

May be worth providing an example of one of the links you are trying to scrape poster & fan art from

:)

**Comment by rod8687** [comment]
I'm using data18 movie
latest version so 0.3.2

example for a link would be http://www.data18.com/movies/1147702
it's actually only saving the .nfo file, nothing else

**Comment by Cutters1982** [comment]
Please can you go to "Preferences -> File Creation" and check that "Write Fanart and Poster Images" is ticked?

Btw, for that movie in question, do you have split scenes of the movie or a single file?

If you have split scenes I suggest viewing the scene index and copying the link for each scene and using the Data18 Web Scraper for that :)

**Comment by rod8687** [comment]
Hi, Thanks for the hint, "write fanart and poster images" is active
it's not even showing the posters after scraping, same if it's automaticly scraping the backcover,
none of the images are being saved, neither for poster, fanart nor for the actor Images. 

movie in question was a single file

here is another example
http://www.data18.com/movies/147608

**Comment by ianmargarone** [comment]
Yes posters and fanart are not being saved or displayed in the GUI.

**Comment by Cutters1982** [comment]
Okay, yeah, I've just tested again myself and you're right, it's not saving the posters & fan art for Data18Movie only (Data18 Web Content scraper is still working fine).

I've also noticed that if you choose to select art manually its only giving you the option of choosing the poster and it skips the fanart.

Hopefully someone can fix this asap then.

**Comment by slappy2** [comment]
Data18 Web Content scraper is no longerl working fine. Actors name are there but no actors url/images.

**Comment by insickin** [comment]
And it's not pulling anny front or back covers.

**Comment by d2dyno** [comment]
I get art just fine, but no actor images.

**Comment by Wizell** [comment]
Should be fixed in v0.3.3
