### ISSUE TITLE
FEATURE REQUEST - Pick Movie

### ISSUE THREAD

**Issue by ciaron88** [DoctorD1501/JAVMovieScraper#225]
Hi

sorry if this has already been requested. this is mainly for DVD movie content

In Kodi when you get the info for a movie if there is more than 1 match you can choose the correct one. can this be added to JAVMovieScraper like the way you can pick the fanart. my files currently don't have the ID in the name and therefor JAVMovieScraper is get the wrong information for some of my movies. i have A LOT of files and i don't want to get the id for each movie i have and it would be a lot easier if i can just pick the right movie if needed while i am getting the info for a movie

Thanks

**Comment by Cutters1982** [comment]
I believe this is available under:-

Preferences -> Scraping Dialogs To Show -> Select Search Results Manually

**Comment by ciaron88** [comment]
oh cool didn't see that

Thanks a lot :)

**Comment by Cutters1982** [comment]
You're welcome :)
