### ISSUE TITLE
Data18 webcontent issue.

### ISSUE THREAD

**Issue by myxtrastufff** [DoctorD1501/JAVMovieScraper#230]
I have noticed that when scrapping web content that doesn't have fan art like the below link it does not create a poster or fanart after writing in the scrapper. Usually the scrapper pulls the main image off the site but it doesn't write it.

http://www.data18.com/content/1195322

The below link would work because there is fan art below the main picture

http://www.data18.com/content/1157023

**Comment by Wizell** [comment]
v0.3.4 should fix this issue
