### ISSUE TITLE
AV Entertainment scraper broken (again)

### ISSUE THREAD

**Issue by unknown12345678** [DoctorD1501/JAVMovieScraper#235]
AV Entertainment scraper no longer working.

**Comment by Wizell** [comment]
I don't see any problem with this scraper, tests are not showing problems and i did a try with MER-03 without any issue.

If there is a problem, create a new issue with details, explain what is not working and give an example.

**Comment by unknown12345678** [comment]
I am using this on Ubuntu 18.04 so that could be the problem. I’ll test again on windows and Ubuntu and report back with a new issue and prescribed template. Cheers.
