### ISSUE TITLE
I can't scrape JAV lib recently

### ISSUE THREAD

**Issue by jraphael11** [DoctorD1501/JAVMovieScraper#254]
I use DMM and R18 usually, but they are not working recently.
Could you fix it?

**Comment by zeldatp151** [comment]
JAVLIB moved to Cloudflare, and JAVMovisScraper hasn't been updated to bypass CF's antibot protections.

**Comment by Wizell** [comment]
as @zeldatp151 mentionned, JMS is not capable of bypassing cloudflare. But i do have some working code to do that. Some deep changes are required to avoid solving cloudflare challenge for each file.

**Comment by Wizell** [comment]
Duplicates #239
