### ISSUE TITLE
Can agent mode be added to software?

### ISSUE THREAD

**Issue by asdf1319964f** [DoctorD1501/JAVMovieScraper#261]
Can agent mode be added to software?

**Comment by asdf1319964f** [comment]
I want the software to act as a proxy. Can you add this function to a version?

**Comment by asdf1319964f** [comment]
Can the proxy function  be supported by the softwares?

>

**Comment by rahadiancs** [comment]
if what you means is to connect the software to the Internet via proxy, you can easily add Java parameter when you run the software.

`java -jar -Dhttp.proxyHost=10.0.0.100 -Dhttp.proxyPort=8800 -Dhttps.proxyHost=10.0.0.100 -Dhttps.proxyPort=8800 JAVMovieScraper.jar`

**Comment by Wizell** [comment]
indeed, proxy can be set at the JVM level as explained by @rahadiancs.

I added a page to explain this as more users may need this information: https://github.com/DoctorD1501/JAVMovieScraper/wiki/Using-a-proxy
