### ISSUE TITLE
Next version update?

### ISSUE THREAD

**Issue by maddog2000** [DoctorD1501/JAVMovieScraper#264]
Hi Wizell.  Thanks for continuing to work on this project.  I noticed that you made a lot of commits 9 days ago.  Do you have a date in mind of when you will release the next version of JAVMovieScraper?

**Comment by Wizell** [comment]
I should be able to release a new version this week. I just want to fix few more things before.

**Comment by marcelhehle** [comment]
Please, please, please include this enhancement:
https://github.com/DoctorD1501/JAVMovieScraper/pull/231

I have a fairly big library that I can't scrape manually any more. Therefore I wrote my own scripts to do the scapring but whenever JAVMovieScarper doesn't identify the movie correctly I currently can't correct this via the cmd-line.

**Comment by Wizell** [comment]
A new version v0.3.6 have been published. Please feel free to test it

**Comment by marcelhehle** [comment]
Did a fresh install of JRE 1.8.0. Now I can scrape successfully, but -scrapeurl returns like above without any feedback or action

```
[plex@pms JAVMovieScraper]$ /usr/bin/java -jar /home/plex/JAVMovieScraper/JAVMovieScraper.jar  -scrapeurl http://www.data18.com/movies/123748
Java(TM) SE Runtime Environment 9.0.4+11(Oracle Corporation) -- 9(Oracle Corporation)
Heap: 3 GB
Free mem: 246 MB
[plex@pms JAVMovieScraper]$ 
```
