### ISSUE TITLE
Caribbeancom not working in version 0.3.6

### ISSUE THREAD

**Issue by maddog2000** [DoctorD1501/JAVMovieScraper#270]
The 0.3.6 version was just released a couple of hours ago.  When I tried out the Caribbeancom scraper, it was able to scrape all the text data such as title, year, release date, ID, studio, plot, genres, and actors, but it was not able to scrape any pictures.  Is this by design?

**Comment by Wizell** [comment]
There is sadly no information on what is the expected behavior for each scraper and there is no test on this one. I don't have time to add tests but this is fixed in master.
