### ISSUE TITLE
Is this project dead? :(

### ISSUE THREAD

**Issue by Cutters1982** [DoctorD1501/JAVMovieScraper#287]
Heya

Just wondered  if there is work behind the scenes on developing this scraper further, it's gone awfully quiet, which is a real shame because there are many possibilities to improve on this.

Hope to hear some news as to what the future plans are with the program :)

**Comment by Borisbee1** [comment]
It's not dead but Wizell is only one man so updates will come when he has the time.  We were just talking about how to fix the Javlibrary scraper here https://github.com/DoctorD1501/JAVMovieScraper/issues/279.  
I've made a few updates myself on my own local copy but I am not very familiar with java and submitting pull requests.  Creating new scrapers isn't too hard either if you take the time to learn.  I'm currently working on scrapers for mgstage.com and jav321.com, and I've fixed a few other scrapers like caribbean premium.  It's just a matter of getting them to a finished state and submitting them to Wizell.

If you're impatient (like I was) I suggest downloading and compiling it for yourself to make necessary changes.

**Comment by zuko7177** [comment]
Thanks to @Wizell and @Borisbee1 for your time on this.  We we moving to Wizell's repository as the "primary" source?

**Comment by Wizell** [comment]
@Cutters1982:  as @Borisbee1 explained the project is not dead but is indeed moving (very) slowly with only few contributors. But hopefully it may change in the future.

@zuko7177: so far @DoctorD1501 is willing to keep this repository active and as the main repository and i don't see problem with it as it avoids confusion. The only drawback so far is the repository configuration which is only accessible to @DoctorD1501 but i think he may do the changes if we ask him. If you believe it would be better to move repository please feel free to explain your point of view so we might consider what is the best course of action.

**Comment by zuko7177** [comment]
Hi @Wizell I noticed there are two pull requests on @DoctorD1501 repository that are open for a while so I was not sure if this repository was still active. So I was not sure which repo was active.

**Comment by Wizell** [comment]
I'm trying to get the PR when i can and when i consider them ready.

I'm sorry that i can't spend so much time on the project but this project is not dead
