### ISSUE TITLE
Not finding proper data / data at all.

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [DoctorD1501/JAVMovieScraper#290]
**Describe the bug**
Not finding proper data / data at all.

**Give an example**

For example 'NHDTB-042 A Big Tits Woman Who Could Not Escape The Feet Tangled And Escaped With Half-ass But Still Be Able To Escape With The Desinated Denim ~ The Grand Entrance Of The Regret Sexual Female SEX ~' is something I can go and look up on JAVLibrary.. but scraping it in JAVMovieScraper doesn't find it. I've tried renaming the file to just the ID, to the complete JAVLibrary title and some other things. Doesn't want to find it.

**Comment by Wizell** [comment]
Should be fixed in 0.3.7. Please feel free to try and report (note the changes in the release note).
