### ISSUE TITLE
[Request] Ability To Choose Selection

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [DoctorD1501/JAVMovieScraper#292]
So if you run a scrape of all the sources, I think it would be a wise idea to allow the user to "select" from what was scraped (Similar to how MusicBrainz works). Because when going through them individually I find the proper one, but when running a full scrape, It's not the correct one. And I understand this has to do with how I have my scrapers sorted, but that's hard to work with because things aren't always consistent.

I also think adding a feature to search or add a link would be nice, as a fallback option incase the scraper isn't auto finding it.

**Comment by fidofido300** [comment]
You Do Have URL Selection 
and url input under preference--->sccraping dialogs to show

**Comment by Z3ROGRAV1TYx** [comment]
Oh, I missed that I guess. My bad.
