### ISSUE TITLE
No more release to fixes javlibrary issue?

### ISSUE THREAD

**Issue by zroaxcel** [DoctorD1501/JAVMovieScraper#296]
Anyway to fix this issue?

**Comment by Wizell** [comment]
I haven't got time to release the patch yet. But one is almost ready.

I actually hope to release it this weekend

**Comment by zroaxcel** [comment]
Thank you very much for the news. I thought this project already dead.

**Comment by Wizell** [comment]
Should be fixed in 0.3.7. Please feel free to try and report (note the changes in the release note).

**Comment by Still34** [comment]
Doesn't seem to work to me. Cookies.txt path is configured as well as user agent.

**Comment by Wizell** [comment]
In order to dig deeper into this matter, can you confirm the following ?
- You accessed javlibrary.com website before creating your cookies.txt file (and you saw the cloudflare challenge being solved by your web browser)
- The cookies.txt contains clearance cookies for javlibrary (you can check for a line containing clearance word and javlibrary)
- the user agent is the exact same as the what would be in HTTP header (e.g. mine is Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0)

**Comment by Still34** [comment]
Yes to all of the above.

**Comment by Wizell** [comment]
I just retried and it seems to work.

Could you post your settings.xml file (it should be next to the executable jar file) and the javlibrary lines in cookies.txt ? (do not post the whole file if it contains cookies for authenticated websites)

**Comment by Still34** [comment]
> I just retried and it seems to work.
> 
> Could you post your settings.xml file (it should be next to the executable jar file) and the javlibrary lines in cookies.txt ? (do not post the whole file if it contains cookies for authenticated websites)

https://hatebin.com/ddkcrhqsug
https://hatebin.com/mmfsspukqm

**Comment by Wizell** [comment]
Is the first line of the pasted cookies.txt really starts with tab character or is it due to copy/paste operations ?

**Comment by Still34** [comment]
No, oops, bad copy-paste.

**Comment by Wizell** [comment]
Comparing from what i have, there also see a missing cookie named __qca. Do you have this cookie in your cookie file ?

**Comment by Wizell** [comment]
You should also note that cookies from cloudflare are only valid about half an hour

**Comment by Still34** [comment]
I don't have that in the first place, no, even after examining the cookies stored in the browser.

**Comment by Wizell** [comment]
Can you check the cookies sent by your browser during the request ? 

In firefox, it's accessible using F12 menu then network, pick a request to javlibrary and open cookies tab

**Comment by Still34** [comment]
```
Host: www.javlibrary.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Referer: http://www.javlibrary.com/en/
Cookie: __cfduid=d1d466aaf068521bf3121957d989519d71565570145; cf_clearance=44850904ae20e1bb5f37a4d8effd25a17406dda6-1565570149-3600-150; timezone=-480; over18=18
Upgrade-Insecure-Requests: 1
```

**Comment by Wizell** [comment]
Ok, i think i got it.
You put "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.145 Safari/537.36 Vivaldi/2.6.1566.49" as a user agent in JAVMS but your web browser send "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

Please can you try to set user agent to "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0" and retry ?

**Comment by Still34** [comment]
Er, that's because I used a different browser just to get the cookies you mentioned.

**Comment by Still34** [comment]
Okay, it works now after I switched to Firefox. For some reason Vivaldi with the cookies didn't seem to work?

**Comment by Wizell** [comment]
For sure the renewable of cookies must be done very often.

I will think of a way to automate this.

Perhaps using the requiring an installed Firefox browser and creating a dedicated profile with a web extention could do the job without user interaction by firing the browser when needed. But it will need some work and test
