### ISSUE TITLE
Scrap the movie in Japanese instead of English does not work

### ISSUE THREAD

**Issue by Masterbaiter** [DoctorD1501/JAVMovieScraper#300]
**Describe the bug**
Translation - "Scrap the movie in Japanese instead of English" does not work properly, Metadata still got translated to English

**Comment by Still34** [comment]
Sometimes it isn't necessarily translated, but the source of the amalgamation returns an English name. You can confirm this by checking the log; it'll tell you where it got the English name from.

**Comment by Masterbaiter** [comment]
Thank you! Problem solved.
