### ISSUE TITLE
Run the jar from Java 11

### ISSUE THREAD

**Issue by sintetico82** [DoctorD1501/JAVMovieScraper#304]
Hello,
If I try to execute on java 11 I have this error:

OpenJDK Runtime Environment 11.0.2-redhat+7-LTS(Oracle Corporation) -- 11(Oracle Corporation)
Heap: 3 GB
Free mem: 252 MB
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel

     
I now that in Java 11 there is not JFX, but I had installed it but I don't understand why still give me this error.

Can some one help me to execute the correct procedure?

**Comment by javfans** [comment]
Ubuntu 18.04, tested with manually installed openjdk-13.0.1_linux-x64_bin.tar.gz and javafx-13.0.1-sdk-linux 

still jfxpanel error

**Comment by Wizell** [comment]
Please look at https://openjfx.io/ to install OpenJFX manualy.

For Linux, it should be provided by your distribution.
For instance on Archlinux you should install jre-openjdk and javaXX-openjfx and on ubuntu you should install openjfx and openjdk-XX-jre

where XX is the JRE version (e.g. 11)
