### ISSUE TITLE
No longer scraping actor thumbs

### ISSUE THREAD

**Issue by jake4dave2** [DoctorD1501/JAVMovieScraper#306]
Just installed the latest version, JavLibrary works using the cookie fix, but I now can't find a way of scraping actor thumbnails. 

I have some previous versions of the Scraper and those are no longer working (for actor thumbs) either, after I installed the new one - so I'm not sure if this is a bug or not, it may be a broken scraper?

R18/DMM don't work when you use them individually and I've tried reorganising their order.

**Comment by fidofido300** [comment]
they were at maintenance Try again

**Comment by jake4dave2** [comment]
Thanks, looks like it is working again, although it is way slower than it was. Taking about 10 seconds longer per scrape, hopefully this will sort itself too.
