### ISSUE TITLE
是否可以添加代理功能？ Is it possible to add proxy functionality?

### ISSUE THREAD

**Issue by hiair2323** [DoctorD1501/JAVMovieScraper#316]
是否可以添加代理功能？因为我的网络需要vpn才可以打开一些网站
Is it possible to add proxy functionality? Because my network needs vpn to open some websites

**Comment by haijiao1945** [comment]
兄弟 给你指条路 本机挂sock代理后 用Proxifier针对javaw.exe进程做代理就可以了

**Comment by sn0wjin19** [comment]
不用，能有更简单的办法
java -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 -jar JAVMovieScraper-v0.3.7.jar
用批处理保存运行这条就行
端口改成梯子的端口，我的这里是7890

**Comment by zuko7177** [comment]
See https://github.com/DoctorD1501/JAVMovieScraper/wiki/Using-a-proxy

**Comment by Wizell** [comment]
This is already done.

Please see the previous message of @zuko7177
