### ISSUE TITLE
Slowly scrape

### ISSUE THREAD

**Issue by burtonfly** [DoctorD1501/JAVMovieScraper#32]
at scape many source so make time slowly
can we have option to select source to scrape to save time ?
Can we grab Info from List URL ?? ex : list url  of JAVlibraly.com ??

**Comment by DoctorD1501** [comment]
This should be possible now as of 7dfe6703a2193acc646b9b553b1717d3cce1ab59. You will need to enable the option in the preferences menu "Provide the URL yourself when scraping". I've also added most of the JAV scrapers to the site specific scraper menu so you can use them by themselves.
