### ISSUE TITLE
Trying to build a jar file

### ISSUE THREAD

**Issue by koonfoon** [DoctorD1501/JAVMovieScraper#328]
Hi, I was trying to build a jar. It is because for last few weeks the DMM scrapping is not working.
But I had read from the "Issues" page, **zuko7177** seem to had fixed this issue.

Hence, I downloaded the whole repo, installed Gradle 6.6, installed java 11, and run the command "gradle build".

But this is the error that I get.

Execution failed for task ':checkstyleMain'.
Unable to create Root Module: config {C:\Users\koonf\Desktop\JAVMovieScraper-master\config\checkstyle\checkstyle.xml}

I am running on Windows 10.

Please help. Thank you.

**Comment by koonfoon** [comment]
Will the build successful if in linux environment instead of Windows?

**Comment by koonfoon** [comment]
build with WLS perhaps.
🙏

**Comment by gamehackerx** [comment]
Did you build the new jar file?
if you did,can you share with me?tks!

**Comment by rickytor81** [comment]
May I ask for the new jar file as well? I failed to generate jar file by using Eclipse. Many thanks!!
