### ISSUE TITLE
Scrapes gone wrong when writing multiple files with one or more unknown videos

### ISSUE THREAD

**Issue by tehwateva** [DoctorD1501/JAVMovieScraper#36]
I noticed this issue while scraping multiple files at once.

For example if the program scrapes 5 files and one of them cannot be found, it will write the file data on the wrong folder/file and skipping the last one.

e.g.

If i were to scrape the following files (only 1 is wrongly named/doesn't exist)

SOE-101 
SOE-200
SOE-9999 (The wrong/non-existant one)
SOE-502
SOE-503

After scraping and clicking on write file data, it will scrape like this : 

SOE-101 (Scraped with the correct info) >
SOE-200 (Scraped with the correct info) >
SOE-9999 (Scraped with the info of SOE-502) >
SOE-502 (Scraped with the info of SOE-503) > 
SOE-503 (no written info at all due to SOE-999 not found)

**Comment by 12floz355** [comment]
I had this same problem, then after seeing a release with it specified as being fixed I tried that... also just now tried v1.2... and it doesn't seem to work still.  This is using the Data18 movie scraper.  Still does exactly what is described by the OP.
