### ISSUE TITLE
Scraping movies with multiple parts

### ISSUE THREAD

**Issue by NapInFever** [DoctorD1501/JAVMovieScraper#38]
Hi, DoctorD! If the file is split in 2 or more parts is there any way to scrape it correctly? In other words can the scraper treat those parts as one file?

**Comment by DoctorD1501** [comment]
It should already be working, although perhaps your naming structure for multiple parts isn't supported. What is the file name you are using? Is it something like My Movie CD1.avi and My Movie CD2.avi?

**Comment by NapInFever** [comment]
Indeed, It seems I was using unsupported naming structure. I used My Movie A.avi and My Movie B.avi structure. When I've tried something with My Movie CD1.avi and My Movie CD2.avi or My Movie part1.avi and My Movie part2.avi it is working just fine. Thanks
