### ISSUE TITLE
Problems with heyzo scraper

### ISSUE THREAD

**Issue by NapInFever** [DoctorD1501/JAVMovieScraper#41]
There are some episodes that exists in both versions of the sites. However there are some videos that only exist in japanese version. The scraper do not find info on these videos  even when I turn the option that forces to scrape in japanese instead of english

**Comment by DoctorD1501** [comment]
Can you leave an example of the ID or URL of such a file?

Thanks.

**Comment by NapInFever** [comment]
For example, this one exists only in jap version:/moviepages/0330/index.html
