### ISSUE TITLE
Incorrect scraping of mutliple actors(caribbeancom scraper)

### ISSUE THREAD

**Issue by NapInFever** [DoctorD1501/JAVMovieScraper#48]
In some videos multiple actresses are treated in the same way as one actress if you scrape in englsih.
Example:010213-226, 050313-328, 080913-401, 112312-191
Still in other videos multiple actresses are scraped correctly
Example:081712-104, 122814-769
I assume the incorrect scraping is happening because  names of actresses are not separated by commas in the aforementioned videos. In Jap version actresses are scraped correctly. Is it possbile to fix this? For example, scrape japanese names and then translate them into english if the actress name is too long.

**Comment by DoctorD1501** [comment]
The new dev build now has a fix so that actor names just come from the translated version of the Japanese page.
