### ISSUE TITLE
Cannot use on mac shared drive

### ISSUE THREAD

**Issue by polardog** [DoctorD1501/JAVMovieScraper#51]
Not able to look for folders on shared drive on mac, but OK if I am using window.

Possible of doing so for Mac as well?

**Comment by DoctorD1501** [comment]
I don't have any good way of testing this. I'm going to mark this as "Helped Wanted" in case there is a developer who has a Mac that can help out.

**Comment by DoctorD1501** [comment]
It looks like to get this to work on Mac, something like vfsjfilechooser2 will need to be used instead of JFileChooser in BrowseDirectoryAction.java.

**Comment by DoctorD1501** [comment]
This should now be fixed in the latest release. Please reopen this ticket or make a new one if you still have this issue.
