### ISSUE TITLE
Scraping Hangs when JAV Movie is not found on R18.com

### ISSUE THREAD

**Issue by PrSinister** [DoctorD1501/JAVMovieScraper#52]
When scraping JAV, it will go through DMM, JAVLibrary, JavZoo, etc.. but when i gets to R18.com, it will stay there forever saying it it got results but that's it. 

Trying the R18.com by itself says that nothing is found.

Example movies:

SDMT-954
SDMU-018

**Comment by PrSinister** [comment]
This is weird... I tried for days to scrape these two and it would always hang on R18.com but last night i started the scrape and went to bed and this morning they were scraped...

**Comment by DoctorD1501** [comment]
I released a few tweaks in a recent commit that may have helped some of the hanging R18 issues. Let me know if you still notice it happening again. Thanks.
