### ISSUE TITLE
Data18 Movie It does not work.

### ISSUE THREAD

**Issue by AiWABR** [DoctorD1501/JAVMovieScraper#54]
I tried to use the scraper to data18 movies, but this is not working.

You can check?

I tried the direct url of the movie and search by name.

**Comment by DoctorD1501** [comment]
What is the name of the movie you are searching for or the URL? Also, I just released a new build on mediafire that had a few bug fixes for Data18 movie scraping, so try to download the build from there first.

**Comment by DoctorD1501** [comment]
I believe this one should be fixed in 28f888954f460d24c0e5953bde3adc1248d8854d. Closing this issue for now. If you are still experiencing issues, please open a new issue.
