### ISSUE TITLE
Blank actors field(1pondo)

### ISSUE THREAD

**Issue by NapInFever** [DoctorD1501/JAVMovieScraper#65]
If you scrape videos in english there is possibility that it won't scrape any actress although the profile with the name is present. From what I've seen the failure occurs with profiles that doesn't have images
Examples:011009_506, 042712_326, 051812_341, 051912_001

**Comment by DoctorD1501** [comment]
Should be fixed now. You can grab the latest build on Mediafire until I release a new full fledged build on the releases page.
