### ISSUE TITLE
Any chance to scrape from Private.com

### ISSUE THREAD

**Issue by polardog** [DoctorD1501/JAVMovieScraper#74]
Movie from private.com is not on Data18.com but can't be scrape from any other sites that movie scrapper currently supports.

Any idea that may help?

Movie - Private Special 108 "Maids for All"

**Comment by DoctorD1501** [comment]
Yeah, it possible to write this scraper, and probably a good idea considering this data is missing from data18 for dvd releases from this company, although I'm not sure how soon I'll get around to it. I'm going to give this a "Help Wanted" tag in case anyone has a burning desire to see it done before I get around to it.

**Comment by Wizell** [comment]
Please use "new scraper request" format in order to help me create new scrapers
