### ISSUE TITLE
Append ID to title for already scrapped files?

### ISSUE THREAD

**Issue by tehwateva** [DoctorD1501/JAVMovieScraper#75]
I know that recently there's an added function to append ID to title when scraping, but I'm wondering if there's a way to append ID to files that have already been scrapped? This is because I don't want to re-scrape all the files that I've already done before this feature was added

**Comment by DoctorD1501** [comment]
Issue fixed in newest build available at: http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

Make sure you have the preference enabled, and then just write the data again on a previously scraped file. You don't need to actually scrape the file itself before clicking write data.
