### ISSUE TITLE
bugs in data18 WebContent

### ISSUE THREAD

**Issue by AiWABR** [DoctorD1501/JAVMovieScraper#76]
In English
Found new bugs in data18 WebContent, you are ready?

Scrapper not appear in the Studio and Movie Set, appear in earlier versions.

Suggestions, it will be possible to add?

Use the end of the link as ID to be able to use in future editions.
example: http://www.data18.com/content/1150577
ID would be 1150577

Using Release date to add release date.
example: http://www.data18.com/content/date-20150520.html
The date would be: 20/5/2015
Note: In the scraper to Kodi once made the request is DoctorD1501 showed me how to add, worked perfect.

For now that's it, thank you in advance for any update and the great work you have done for a long time in scrapper and program for adult content.

---------------

Em Português:

Encontrei novos bugs no data18 WebContent, tem como arrumar?

No scrapper não aparece o Studio e Movie Set, apareceria em versões anteriores.

Sugestões, sera possivel adicionar?

Usar o final do link como ID para poder usar em futuras edições.
exemplo: http://www.data18.com/content/1150577 
ID seria 1150577 

Usar o Release date para adicionar data de lançamento.
exemplo:  http://www.data18.com/content/date-20150520.html
A data ficaria: 2015-05-20
Observação: No scraper para Kodi uma vez fiz o pedido é o DoctorD1501 me mostrou como adicionar, funcionava perfeito.

Por enquanto é isso, agradeço desde já por qualquer atualização e pelo ótimo trabalho que tem feito a um bom tempo no scrapper e no programa para conteudo adulto.

**Comment by DoctorD1501** [comment]
The newest build from mediafire has a fix for the broken set and studio fields on data18.

As for the release date, while I could scrape it, there's no valid way for XBMC or Kodi to read this data, so I would be creating invalid elements in the nfo. Do you know of any software that actually reads the <releasedate> tag? Why do we need it if we can't read it anywhere?

**Comment by AiWABR** [comment]
In English
Thanks for the corrections and have added some things.

The release date for films is not actually used, but when I used the scraper in Kodi added the Director Tag and then edited all nfo's to use as serial (TV Show), because at least for me is more beautiful and more organized. The dates also help to give the right order in the episode, since we do not have a website to organize videos using to episode has a certain number (example: s01e35 or s2015e35).

Thank you again.

--------

Em Português:

Obrigado pelas correções e por ter adicionado algumas coisas.

A Data de lançamento para filmes não é usado realmente, mas quando eu usava o scraper no Kodi adicionava na Tag Diretor e depois editava todas as nfo´s para utilizar como seriados (TV Show), pois pelo menos para mim fica mais bonito e mais organizado. As datas também ajudam para dar a ordem certa no episodio, já que não temos um site que organizar os vídeos usando para episodio tem numero certo (exemplo: s01e35 ou s2015e35).

Obrigado novamente.

**Comment by DoctorD1501** [comment]
Added ability to scrape and display release date as part of the releasedate tag in c98f600797d7de31feb4b126cd1017a3d50b99af. Other programs may not be able to read this tag, but this one at least will.
