### ISSUE TITLE
Full release date?

### ISSUE THREAD

**Issue by noisyscott** [DoctorD1501/JAVMovieScraper#78]
Hello, 

Love JAVMovieScraper.  Thanks for all of the work.

I have been cataloging movies by full release dates.  This comes in handy since some stars can make many movies in a year...or even a single month!  Would it be possible to add full date scraping and map it to the "date" or "premiered" tags?

Thanks,
Scott

**Comment by DoctorD1501** [comment]
The problem is that, so far as I am aware, that tag only works for tv shows - not movies. XBMC/Kodi itself doesn't support the air date/ premiered / release date tag for movies, although if they ever did, I would be happy to add this feature in...

**Comment by DoctorD1501** [comment]
Added in c98f600797d7de31feb4b126cd1017a3d50b99af. Other programs may not be able to read this tag, but this one at least will.
