### ISSUE TITLE
Poster/fanart missing from some Movie scenes

### ISSUE THREAD

**Issue by d2dyno** [DoctorD1501/JAVMovieScraper#82]
Not sure if related to previous issue, but when scraping a individual scene, from a movie, the file now scrapes. However, some (and I mean only some) are still struggling. For example, below is a debugger log output of one such file. Not sure what can be done here.

https://gist.github.com/d2dyno/b4709c99b7634b391320

**Comment by DoctorD1501** [comment]
The newest dev build should have a fix for this now.
