### ISSUE TITLE
[Bug] Limit file rename length

### ISSUE THREAD

**Issue by d2dyno** [DoctorD1501/JAVMovieScraper#84]
Just ran into an issue, where a scraped file had many actors in it, and the file was renamed (according to preference). However, the filename was so long, I had to use a 3rd party (non Explorer.exe) program to edit the file names, to even be able to delete them. I noticed this issue, because the images weren't being written.

I believe a tangible solution, would be to limit how many characters the program is able to use, in a file rename (255 would be good for windows), and possibly alert users when their rename settings will make the filename too long/name will be truncated.

Here's the log from when this issue occurred: https://gist.github.com/d2dyno/9e8b71bb2926526adceb

**Comment by DoctorD1501** [comment]
Can you try the latest build from mediafire (0.1.36) and see if this fixes the issue for you?

**Comment by DoctorD1501** [comment]
This issue should be fixed now. Let me know if you still notice a problem with this.
