### ISSUE TITLE
1pondo new web layout!

### ISSUE THREAD

**Issue by nk0304** [DoctorD1501/JAVMovieScraper#87]
Hello!

First of all, thank you for your hard work to create awesome scraper. Btw, 1pondo just updated new web layout, imo, it's better compare to the old one, it's has everything, genre, description, actress name etc but format of title also change, it's no longer 02xxxx-xxx. Please update scraper for this new layout, i really hope it can scrape in Japanese too if possibe because laoyang945 scraper is also out of dated. Sry for my english, hope you can understand. Keep up the good work xD

**Comment by DoctorD1501** [comment]
I fixed the broken posters at least in 9549e057ce2849c34de4b65a717b399d2e78a996 but the new site layout will take longer. I need to figure out how to recognize that the format of the title has changed and keep the old format compatible as well.

**Comment by nk0304** [comment]
Thanks DoctorD!

You can use old format title, it will auto redirect you to the new format title, for excample 1pondo.tv/moviepages/070915_111/index.htm, it will redirect you to http://www.1pondo.tv/movies/3189/ so i think you can still use old format title. Hope it will help.

**Comment by Wizell** [comment]
1pondo changed back to the XXXXXX_XXX
