### ISSUE TITLE
bugs in data18 WebContent

### ISSUE THREAD

**Issue by AiWABR** [DoctorD1501/JAVMovieScraper#90]
-English:
Found new bugs in data18 WebContent

- Not being saved the year it was released the video.
- I do not know if he decided to remove the Release Date, but it does not appear in any scraper I did.

Requests / Suggestions
The title of the video also appears the id of the video, it will be possible only leave the title?

Once again congratulations on the great work you have done. Accompany from the beginning.

-Portugues:
Encontrei novos bugs no data18 WebContent

Não esta sendo salva o ano que foi lançado o vídeo.
Não sei se resolveu remover o Release Date, mas o mesmo não aparece em nenhum scraper que fiz.

Pedidos/Sugestões
No titulo do vídeo aparece também o id do vídeo, sera possivel deixar somente o titulo?

Mais uma vez parabéns pelo ótimo trabalho que tem feito. Acompanho desde o inicio.

**Comment by DoctorD1501** [comment]
Are you using the newest version of the program? I'm not seeing any problem with the year or release date. If you're using the newest version of the program, what is the URL of the file you are trying to scrape?

I'm also not seeing the problem with the title of the video appearing with the ID. Make sure you have "Append ID to Start of Title When Scraping" turned off in the preference menu and try again.

**Comment by DoctorD1501** [comment]
Closing this issue as I think the issues have been resolved already in other commits I made.
