### ISSUE TITLE
Ability to add folders to rename.

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#91]
Right now I move folders manually. But being able to have them moved for me would be great.
Example Base Folder(Website)\Studio(Kink)\Movie Set(Whipped Ass)\Year(2014)\<RELEASEDATE> - <TITLE>. This is my folder structure for web scenes.

**Comment by DoctorD1501** [comment]
Added this in 4d6d95a15b566d2a8f9e98edd1a87a45bc73736e.
