### ISSUE TITLE
Multiple files scraping problem when movie not found reappear in  v0.2.00-alpha

### ISSUE THREAD

**Issue by rrkyd** [DoctorD1501/JAVMovieScraper#92]
Hi DoctorD1501 

v0.2.00-alpha works great but the problem mentioned in #55 reappeared. I assumed all you need to do is add "null" in array for these movies.

**Comment by DoctorD1501** [comment]
Hey rrkyd,

Please try my newest build from http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar which should fix the issue. Do you still notice the problem with this build?

Thanks.
