### ISSUE TITLE
Renaming files not working

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#94]
It's moving to the folders fine. Except it's not renaming the files to <RELEASEDATE> - <TITLE>. Instead it's adding them to a folder named <RELEASEDATE> - <TITLE> then the original file name inside that.

**Comment by DoctorD1501** [comment]
I think this is a duplicate of Issue #80, but it's on my list of things to improve.

That said, you can probably load things up in a program like ember media manager once things have been completely scraped in Jav Move Scraper to get better renaming than I currently have in my program at least until I get this addressed.

**Comment by mjsmjs** [comment]
I don't think it's a dup of #80. Before when clicking write file data it would rename the files and add the meta data. But now its moving it to a folder and leaving the file names untouched. Like if I clicked Move file to new folder.

**Comment by DoctorD1501** [comment]
Hey mjsmjs,

Please try the newest build from  http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

I believe I have fixed the issue you brought up, but please let me know if you notice any further issues.

Thank you,
DoctorD

**Comment by mjsmjs** [comment]
Thanks. Works just perfect.
