### ISSUE TITLE
Can't scrape from data18 webcontent

### ISSUE THREAD

**Issue by polardog** [DoctorD1501/JAVMovieScraper#96]
Failed to scrape from data18 web content for the movie 
Cheating Blonde Wife Fucks Husbands Black Friend

Any idea?

**Comment by DoctorD1501** [comment]
It works fine for me. Make sure you're on the newest release and that you're selecting data 18 web content and not data 18 movie from the scraper list.

If you're still having a problem, enable the output panel in the "View" menu and please paste your log.

Thanks.

**Comment by polardog** [comment]
Still can't

I try downloading the latest version and scrape using web content but not video
The correct link on data18 should be http://www.data18.com/content/1151982
But the scraper gave me http://www.data18.com/content/1148701

Enclosed is the log
Appreciate your help
====================================
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Read in amalgamation preferences from AmalgamationSettings.json
Gui Initialized
Read in amalgamation preferences from AmalgamationSettings.json
currentItemSource = Data18 Web Content with disabled = false
currentItemSource = Default Data Item Source with disabled = false
fileBaseName = Cheating Blonde Wife Fucks Husbands Black Friend
searchString = http://www.data18.com/search/?k=Cheating+Blonde+Wife+Fucks+Husbands+Black+Friend&t=0
Scraping this webpage for movie: http://www.data18.com/content/1148701
Movie scraped = Movie [title=Title [title="Cheating Blonde GF Barely Takes BBC in Her Ass" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="Blacked" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="2015" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="Zoey had a date after work with a guy she met a few days ago. Her date was in downtown but she lived far away from there so she asked her friend Jessica who lived close by if she could come over and take a quick shower after work. However once Zoey got to her friends apartment only her boyfriend Flash was there. She always had a crush on him so she decided to leave the bathroom door open while she was taking a shower. Flash knew what she was up to so he got naked and met her in the shower. She instantly started sucking on his huge black dick and gagging on it because it was too big for her mouth. After a while he took her in the bedroom and fucked her really hard, at that moment Zoey wanted to be extra naughty and asked him to fuck her ass. She really struggled to handle him in her tight pink asshole but she did for a bit. She couldn't believe she let her friends boyfriend fuck all her holes before a date but she loved it. Naughty update there!" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="Blacked" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="2015-03-10" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], fanart=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], extrafanart = [Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1148701" source="Data18 Web Content"], genres=[Genre [genre="Heterosexual" source="Data18 Web Content"], Genre [genre="Hardcore" source="Data18 Web Content"], Genre [genre="Anal" source="Data18 Web Content"], Genre [genre="Interracial" source="Data18 Web Content"], Genre [genre="Boy Girl" source="Data18 Web Content"], Genre [genre="Black Men" source="Data18 Web Content"], Genre [genre="Caucasian" source="Data18 Web Content"]], actors=[Actor [role="null", Person [name="Zoey Monroe", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/23832.jpg" source="Default Data Item Source"]] source="Data18 Web Content"], Actor [role="null", Person [name="Flash Brown", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/17102.jpg" source="Default Data Item Source"]] source="Data18 Web Content"]], directors=[]]
Scraping complete of siteScraper = Data18 Web Content
Read in amalgamation preferences from AmalgamationSettings.json
Skipping amalgamation process as there is only one movie
Setting new movie: Movie [title=Title [title="Cheating Blonde GF Barely Takes BBC in Her Ass" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="Blacked" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="2015" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="Zoey had a date after work with a guy she met a few days ago. Her date was in downtown but she lived far away from there so she asked her friend Jessica who lived close by if she could come over and take a quick shower after work. However once Zoey got to her friends apartment only her boyfriend Flash was there. She always had a crush on him so she decided to leave the bathroom door open while she was taking a shower. Flash knew what she was up to so he got naked and met her in the shower. She instantly started sucking on his huge black dick and gagging on it because it was too big for her mouth. After a while he took her in the bedroom and fucked her really hard, at that moment Zoey wanted to be extra naughty and asked him to fuck her ass. She really struggled to handle him in her tight pink asshole but she did for a bit. She couldn't believe she let her friends boyfriend fuck all her holes before a date but she loved it. Naughty update there!" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="Blacked" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="2015-03-10" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], fanart=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], extrafanart = [Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1148701" source="Data18 Web Content"], genres=[Genre [genre="Heterosexual" source="Data18 Web Content"], Genre [genre="Hardcore" source="Data18 Web Content"], Genre [genre="Anal" source="Data18 Web Content"], Genre [genre="Interracial" source="Data18 Web Content"], Genre [genre="Boy Girl" source="Data18 Web Content"], Genre [genre="Black Men" source="Data18 Web Content"], Genre [genre="Caucasian" source="Data18 Web Content"]], actors=[Actor [role="null", Person [name="Zoey Monroe", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/23832.jpg" source="Default Data Item Source"]] source="Data18 Web Content"], Actor [role="null", Person [name="Flash Brown", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/17102.jpg" source="Default Data Item Source"]] source="Data18 Web Content"]], directors=[]]
Read in amalgamation preferences from AmalgamationSettings.json
currentItemSource = Data18 Web Content with disabled = false
fileBaseName = Cheating Blonde Wife Fucks Husbands Black Friend
currentItemSource = Default Data Item Source with disabled = false
searchString = http://www.data18.com/search/?k=Cheating+Blonde+Wife+Fucks+Husbands+Black+Friend&t=0
Scraping this webpage for movie: http://www.data18.com/content/1148701
Movie scraped = Movie [title=Title [title="Cheating Blonde GF Barely Takes BBC in Her Ass" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="Blacked" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="2015" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="Zoey had a date after work with a guy she met a few days ago. Her date was in downtown but she lived far away from there so she asked her friend Jessica who lived close by if she could come over and take a quick shower after work. However once Zoey got to her friends apartment only her boyfriend Flash was there. She always had a crush on him so she decided to leave the bathroom door open while she was taking a shower. Flash knew what she was up to so he got naked and met her in the shower. She instantly started sucking on his huge black dick and gagging on it because it was too big for her mouth. After a while he took her in the bedroom and fucked her really hard, at that moment Zoey wanted to be extra naughty and asked him to fuck her ass. She really struggled to handle him in her tight pink asshole but she did for a bit. She couldn't believe she let her friends boyfriend fuck all her holes before a date but she loved it. Naughty update there!" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="Blacked" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="2015-03-10" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], fanart=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], extrafanart = [Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1148701" source="Data18 Web Content"], genres=[Genre [genre="Heterosexual" source="Data18 Web Content"], Genre [genre="Hardcore" source="Data18 Web Content"], Genre [genre="Anal" source="Data18 Web Content"], Genre [genre="Interracial" source="Data18 Web Content"], Genre [genre="Boy Girl" source="Data18 Web Content"], Genre [genre="Black Men" source="Data18 Web Content"], Genre [genre="Caucasian" source="Data18 Web Content"]], actors=[Actor [role="null", Person [name="Zoey Monroe", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/23832.jpg" source="Default Data Item Source"]] source="Data18 Web Content"], Actor [role="null", Person [name="Flash Brown", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/17102.jpg" source="Default Data Item Source"]] source="Data18 Web Content"]], directors=[]]
Scraping complete of siteScraper = Data18 Web Content
Read in amalgamation preferences from AmalgamationSettings.json
Skipping amalgamation process as there is only one movie
Setting new movie: Movie [title=Title [title="Cheating Blonde GF Barely Takes BBC in Her Ass" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="Blacked" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="2015" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="Zoey had a date after work with a guy she met a few days ago. Her date was in downtown but she lived far away from there so she asked her friend Jessica who lived close by if she could come over and take a quick shower after work. However once Zoey got to her friends apartment only her boyfriend Flash was there. She always had a crush on him so she decided to leave the bathroom door open while she was taking a shower. Flash knew what she was up to so he got naked and met her in the shower. She instantly started sucking on his huge black dick and gagging on it because it was too big for her mouth. After a while he took her in the bedroom and fucked her really hard, at that moment Zoey wanted to be extra naughty and asked him to fuck her ass. She really struggled to handle him in her tight pink asshole but she did for a bit. She couldn't believe she let her friends boyfriend fuck all her holes before a date but she loved it. Naughty update there!" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="Blacked" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="2015-03-10" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], fanart=[Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], extrafanart = [Thumb [thumbURL=http://74.50.117.45/338/2984/148701/01.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/02.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/03.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/04.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/05.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/06.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/07.jpg" source="Data18 Web Content"], Thumb [thumbURL=http://74.50.117.45/338/2984/148701/08.jpg" source="Data18 Web Content"]], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1148701" source="Data18 Web Content"], genres=[Genre [genre="Heterosexual" source="Data18 Web Content"], Genre [genre="Hardcore" source="Data18 Web Content"], Genre [genre="Anal" source="Data18 Web Content"], Genre [genre="Interracial" source="Data18 Web Content"], Genre [genre="Boy Girl" source="Data18 Web Content"], Genre [genre="Black Men" source="Data18 Web Content"], Genre [genre="Caucasian" source="Data18 Web Content"]], actors=[Actor [role="null", Person [name="Zoey Monroe", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/23832.jpg" source="Default Data Item Source"]] source="Data18 Web Content"], Actor [role="null", Person [name="Flash Brown", thumb=Thumb [thumbURL=http://img.data18.com/images/stars/120/17102.jpg" source="Default Data Item Source"]] source="Data18 Web Content"]], directors=[]]

**Comment by DoctorD1501** [comment]
The titles of those files are similar, so the search is getting confused. Try checking the preference setting "Provide the URL yourself while scraping" and just paste in the URL of the page that is the correct one. There's not a lot I can do for cases like this unfortunately because we are at the mercy of a poor search engine. :(
