### ISSUE TITLE
Data18 extra genres

### ISSUE THREAD

**Issue by pr0nNDal** [DoctorD1501/JAVMovieScraper#98]
First, love this utility, huge props. The issue I'm bringing up is a mere annoyance.

The Data18 scraper seems to be pulling some of the purchase links on the webpage and writing them as <genre> tags in the NFO. For instance the movie http://www.data18.com/movies/174341 had the following genre tags written to the NFO in JAVMovieScraper 0.1.36-Alpha: Blowjob, Interracial, Gonzo, Shaved, Big Cocks. But using 2.03-Alpha, it adds Back Cover, Play Trailer, Join New Sensations, BUY SD $16.99, BUY 60 Minutes $9.99 and many more. Basically there are links for various external websites and for renting, purchasing the digital comment and the scraper is grabbing those links and generating <genre> tags for them. Looks like the issue exists on all of the 0.2.xx versions.

Thanks for all the hard work, sorry to dump more on you (would lend a hand if I could code for anything, but I would just make things worse I'm sure).

**Comment by DoctorD1501** [comment]
Hey pr0NDal,

Thanks for the bug report.

I've uploaded a new build which should have a fix for this issue. You can download it from http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

Please let me know if it causes issues with genres on other pages or isn't working for you.

Thanks.

**Comment by pr0nNDal** [comment]
Wow, that is incredible. Never expected to get a fix so quickly, thank you so much, really appreciate it.

**Comment by DoctorD1501** [comment]
Cool, glad it worked. Closing the issue.
